//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EditDivineEq.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EdDivText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EdDivText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EditDivineEq.Resources.EdDivText", typeof(EdDivText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Am I.
        /// </summary>
        public static string Eq_AmI {
            get {
                return ResourceManager.GetString("Eq_AmI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Eq_he {
            get {
                return ResourceManager.GetString("Eq_he", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Eq_her {
            get {
                return ResourceManager.GetString("Eq_her", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Eq_herself {
            get {
                return ResourceManager.GetString("Eq_herself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Eq_him {
            get {
                return ResourceManager.GetString("Eq_him", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Eq_himself {
            get {
                return ResourceManager.GetString("Eq_himself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Eq_his {
            get {
                return ResourceManager.GetString("Eq_his", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Eq_Husband {
            get {
                return ResourceManager.GetString("Eq_Husband", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Eq_me {
            get {
                return ResourceManager.GetString("Eq_me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Eq_my {
            get {
                return ResourceManager.GetString("Eq_my", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Eq_myself {
            get {
                return ResourceManager.GetString("Eq_myself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Eq_she {
            get {
                return ResourceManager.GetString("Eq_she", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Eq_them {
            get {
                return ResourceManager.GetString("Eq_them", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Eq_they {
            get {
                return ResourceManager.GetString("Eq_they", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Eq_us {
            get {
                return ResourceManager.GetString("Eq_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Eq_we {
            get {
                return ResourceManager.GetString("Eq_we", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Eq_Wife {
            get {
                return ResourceManager.GetString("Eq_Wife", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Eq0 {
            get {
                return ResourceManager.GetString("Eq0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Eq1 {
            get {
                return ResourceManager.GetString("Eq1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Eq1Feng0 {
            get {
                return ResourceManager.GetString("Eq1Feng0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Eq1Feng1 {
            get {
                return ResourceManager.GetString("Eq1Feng1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Eq1Feng2 {
            get {
                return ResourceManager.GetString("Eq1Feng2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Eq1Feng3 {
            get {
                return ResourceManager.GetString("Eq1Feng3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Eq1Feng4 {
            get {
                return ResourceManager.GetString("Eq1Feng4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Eq1Feng5 {
            get {
                return ResourceManager.GetString("Eq1Feng5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Eq2 {
            get {
                return ResourceManager.GetString("Eq2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Eq3 {
            get {
                return ResourceManager.GetString("Eq3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Eq4 {
            get {
                return ResourceManager.GetString("Eq4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Eq5 {
            get {
                return ResourceManager.GetString("Eq5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EqAidMain {
            get {
                return ResourceManager.GetString("EqAidMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EqAm_I {
            get {
                return ResourceManager.GetString("EqAm_I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EqAnd {
            get {
                return ResourceManager.GetString("EqAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EqBaby0 {
            get {
                return ResourceManager.GetString("EqBaby0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EqBaby1 {
            get {
                return ResourceManager.GetString("EqBaby1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EqBoy {
            get {
                return ResourceManager.GetString("EqBoy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EqBrother {
            get {
                return ResourceManager.GetString("EqBrother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EqChange {
            get {
                return ResourceManager.GetString("EqChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EqChild {
            get {
                return ResourceManager.GetString("EqChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EqDateUnit {
            get {
                return ResourceManager.GetString("EqDateUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EqDuration {
            get {
                return ResourceManager.GetString("EqDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EqExboy {
            get {
                return ResourceManager.GetString("EqExboy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EqExgirl {
            get {
                return ResourceManager.GetString("EqExgirl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EqExHusband {
            get {
                return ResourceManager.GetString("EqExHusband", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EqExWife {
            get {
                return ResourceManager.GetString("EqExWife", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EqFeng0 {
            get {
                return ResourceManager.GetString("EqFeng0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EqFeng1 {
            get {
                return ResourceManager.GetString("EqFeng1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EqFeng2 {
            get {
                return ResourceManager.GetString("EqFeng2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EqFeng3 {
            get {
                return ResourceManager.GetString("EqFeng3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EqFeng4 {
            get {
                return ResourceManager.GetString("EqFeng4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EqFeng5 {
            get {
                return ResourceManager.GetString("EqFeng5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EqGirl {
            get {
                return ResourceManager.GetString("EqGirl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EqHe {
            get {
                return ResourceManager.GetString("EqHe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EqHer {
            get {
                return ResourceManager.GetString("EqHer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EqHerself {
            get {
                return ResourceManager.GetString("EqHerself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EqHimself {
            get {
                return ResourceManager.GetString("EqHimself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EqHis {
            get {
                return ResourceManager.GetString("EqHis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EqI {
            get {
                return ResourceManager.GetString("EqI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EqMain {
            get {
                return ResourceManager.GetString("EqMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EqMary0 {
            get {
                return ResourceManager.GetString("EqMary0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EqMary1 {
            get {
                return ResourceManager.GetString("EqMary1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EqMary2 {
            get {
                return ResourceManager.GetString("EqMary2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EqMary3 {
            get {
                return ResourceManager.GetString("EqMary3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EqMatch0 {
            get {
                return ResourceManager.GetString("EqMatch0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EqMatch1 {
            get {
                return ResourceManager.GetString("EqMatch1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EqMatch2 {
            get {
                return ResourceManager.GetString("EqMatch2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EqMatch3 {
            get {
                return ResourceManager.GetString("EqMatch3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EqMe {
            get {
                return ResourceManager.GetString("EqMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EqMissX {
            get {
                return ResourceManager.GetString("EqMissX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EqMrsX {
            get {
                return ResourceManager.GetString("EqMrsX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EqMrX {
            get {
                return ResourceManager.GetString("EqMrX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EqMy {
            get {
                return ResourceManager.GetString("EqMy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EqMyao {
            get {
                return ResourceManager.GetString("EqMyao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EqMyself {
            get {
                return ResourceManager.GetString("EqMyself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EqOfficer {
            get {
                return ResourceManager.GetString("EqOfficer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EqOfMy {
            get {
                return ResourceManager.GetString("EqOfMy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EqOrgan0 {
            get {
                return ResourceManager.GetString("EqOrgan0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EqOrgan1 {
            get {
                return ResourceManager.GetString("EqOrgan1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EqOrgan10 {
            get {
                return ResourceManager.GetString("EqOrgan10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EqOrgan11 {
            get {
                return ResourceManager.GetString("EqOrgan11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EqOrgan2 {
            get {
                return ResourceManager.GetString("EqOrgan2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EqOrgan3 {
            get {
                return ResourceManager.GetString("EqOrgan3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EqOrgan4 {
            get {
                return ResourceManager.GetString("EqOrgan4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EqOrgan5 {
            get {
                return ResourceManager.GetString("EqOrgan5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EqOrgan6 {
            get {
                return ResourceManager.GetString("EqOrgan6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EqOrgan7 {
            get {
                return ResourceManager.GetString("EqOrgan7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EqOrgan8 {
            get {
                return ResourceManager.GetString("EqOrgan8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EqOrgan9 {
            get {
                return ResourceManager.GetString("EqOrgan9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EqParent {
            get {
                return ResourceManager.GetString("EqParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EqPlayboy {
            get {
                return ResourceManager.GetString("EqPlayboy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EqPlaygirl {
            get {
                return ResourceManager.GetString("EqPlaygirl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EqSelect {
            get {
                return ResourceManager.GetString("EqSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EqSgua {
            get {
                return ResourceManager.GetString("EqSgua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EqShe {
            get {
                return ResourceManager.GetString("EqShe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EqSMyao {
            get {
                return ResourceManager.GetString("EqSMyao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EqSyao {
            get {
                return ResourceManager.GetString("EqSyao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EqT_Date {
            get {
                return ResourceManager.GetString("EqT_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EqT_Hour {
            get {
                return ResourceManager.GetString("EqT_Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EqT_Month {
            get {
                return ResourceManager.GetString("EqT_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EqT_Year {
            get {
                return ResourceManager.GetString("EqT_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EqThem {
            get {
                return ResourceManager.GetString("EqThem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EqThey {
            get {
                return ResourceManager.GetString("EqThey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EqUs {
            get {
                return ResourceManager.GetString("EqUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EqVice {
            get {
                return ResourceManager.GetString("EqVice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EqWe {
            get {
                return ResourceManager.GetString("EqWe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EqWealth0 {
            get {
                return ResourceManager.GetString("EqWealth0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EqWealth1 {
            get {
                return ResourceManager.GetString("EqWealth1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EqWealth2 {
            get {
                return ResourceManager.GetString("EqWealth2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EqWealth3 {
            get {
                return ResourceManager.GetString("EqWealth3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EqWealth4 {
            get {
                return ResourceManager.GetString("EqWealth4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EqWealth5 {
            get {
                return ResourceManager.GetString("EqWealth5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EqWealth6 {
            get {
                return ResourceManager.GetString("EqWealth6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EqWife {
            get {
                return ResourceManager.GetString("EqWife", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EqYgua {
            get {
                return ResourceManager.GetString("EqYgua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EqYMyao {
            get {
                return ResourceManager.GetString("EqYMyao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EqYyao {
            get {
                return ResourceManager.GetString("EqYyao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string szDays0 {
            get {
                return ResourceManager.GetString("szDays0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string szDays1 {
            get {
                return ResourceManager.GetString("szDays1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string szDays10 {
            get {
                return ResourceManager.GetString("szDays10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string szDays12 {
            get {
                return ResourceManager.GetString("szDays12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string szDays13 {
            get {
                return ResourceManager.GetString("szDays13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string szDays14 {
            get {
                return ResourceManager.GetString("szDays14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string szDays15 {
            get {
                return ResourceManager.GetString("szDays15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string szDays16 {
            get {
                return ResourceManager.GetString("szDays16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string szDays17 {
            get {
                return ResourceManager.GetString("szDays17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string szDays18 {
            get {
                return ResourceManager.GetString("szDays18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string szDays19 {
            get {
                return ResourceManager.GetString("szDays19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string szDays20 {
            get {
                return ResourceManager.GetString("szDays20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string szDays21 {
            get {
                return ResourceManager.GetString("szDays21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string szDays22 {
            get {
                return ResourceManager.GetString("szDays22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string szDays23 {
            get {
                return ResourceManager.GetString("szDays23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string szDays24 {
            get {
                return ResourceManager.GetString("szDays24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string szDays25 {
            get {
                return ResourceManager.GetString("szDays25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string szDays26 {
            get {
                return ResourceManager.GetString("szDays26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string szDays27 {
            get {
                return ResourceManager.GetString("szDays27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string szDays28 {
            get {
                return ResourceManager.GetString("szDays28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string szDays3 {
            get {
                return ResourceManager.GetString("szDays3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string szDays4 {
            get {
                return ResourceManager.GetString("szDays4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string szDays5 {
            get {
                return ResourceManager.GetString("szDays5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string szDays6 {
            get {
                return ResourceManager.GetString("szDays6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string szDays7 {
            get {
                return ResourceManager.GetString("szDays7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string szDays8 {
            get {
                return ResourceManager.GetString("szDays8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string szDays9 {
            get {
                return ResourceManager.GetString("szDays9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string szHours12 {
            get {
                return ResourceManager.GetString("szHours12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string szHours16 {
            get {
                return ResourceManager.GetString("szHours16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string szHours20 {
            get {
                return ResourceManager.GetString("szHours20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string szHours24 {
            get {
                return ResourceManager.GetString("szHours24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string szHours4 {
            get {
                return ResourceManager.GetString("szHours4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string szHours6 {
            get {
                return ResourceManager.GetString("szHours6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string szHours8 {
            get {
                return ResourceManager.GetString("szHours8", resourceCulture);
            }
        }
    }
}
