//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EditDivineEq.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FengShuiText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FengShuiText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EditDivineEq.Resources.FengShuiText", typeof(FengShuiText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How is the effect of &lt;my&gt; futue [Wealth + Self-Health] luck to be influenced by Feng Shui overall layout in &lt;my&gt; currently living house space at [630 W. Huntington Dr. 228-Apt. Arcadia Ca.] in coming [12 years]... ?[Feng Shui Effects : Select My Wealth + Self-Health|EqFeng6(Xm),Living House at : Living house address(Ya9.ho.lv),Predict Duration : Select Duration(Tr),Living Peace/Health : (S=x),Wealth Luck : (W@wx)]{AD}&lt;Sn=/Y9a/Xm/Ww@&gt;80.0.
        /// </summary>
        public static string FengShui000 {
            get {
                return ResourceManager.GetString("FengShui000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;I&gt; plan to [buy] this living house at [1131 S. Baldwin ave. C-Ste. Arcadia Ca.81007]... How the current Feng Shui overall layout effect of &lt;my&gt; future [Wealth + Self-Health] luck will be influenced in coming [12 years]... ?[: To rent or To buy,Living Houe at : Realeaste address(Y9a.ho.lv),Feng Shui Effects : Select My Wealth + Self-Health|EqFeng6(Xm),Predict Duration : Select Duration(Tr),Living Peace/Health : (S=x),Wealth Luck : (W@wx)]{AD}&lt;Sn=/Y9a/W@w&gt;80.0.
        /// </summary>
        public static string FengShui001 {
            get {
                return ResourceManager.GetString("FengShui001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to relocate 5 elements(Metal, Wood, Water, Fire, Earth) in Feng Shui overall layout to remove bad effect and to enhence &lt;my&gt; future [Wealth without harming Health] luck at living house at [1131 S. Baldwin ave. C-Ste. Arcadia Ca.81007] ?[Feng Shui Effects : Select My Wealth without harming Health|Eq1Feng6(Xm),Living House at : Living home address(Y9a.lv.ho),Living Peace/Health : (S=x),Wealth luck : (W@wx)]{A}&lt;Sn=/Y9a.lv/W@w&gt;80.0.
        /// </summary>
        public static string FengShui002 {
            get {
                return ResourceManager.GetString("FengShui002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After relocate 5 elements(Metal, Wood, Water, Fire, Earth) in Feng Shui overall layout at [1131 S. Baldwin ave. C-Ste. Arcadia Ca.81007] ... How is &lt;my&gt; expecting [Wealth without harming Health] being enhenced... How long these Feng Shui overall layout can be sustained ?[Living House at : Living home address(Y9a.et),Feng Shui Effects : Select My Wealth without harming Health|Eq1Feng6(Xm),Living Peace/Health : (S=x),Wealth luck : (W@wx)]{AR}&lt;Sn=/Y9a.lv/W@w&gt;80.0.
        /// </summary>
        public static string FengShui003 {
            get {
                return ResourceManager.GetString("FengShui003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How is the current Feng Shui overall layout to influent the products selling for &lt;my&gt; [Boy &amp; Girl dress store] business running at [11230 Garvey ave. H-Ste. El Monte Ca.91733] in coming [12 years] ?[Running Business : Business description and Name(Ss.et),Feng Shui at : Running Business address(Y9a.se.go),Predict Duration : Select Duration(Tr),Attracting Customer : (C&amp;x),Wealth Luck : (W@w+x)]{AD}&lt;Ss.et/Y9a/C&amp;/Ww@+&gt;80.0.
        /// </summary>
        public static string FengShui004 {
            get {
                return ResourceManager.GetString("FengShui004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;I&gt; plan to [rent] this store at [11230 Garvey ave. H-Ste. El Monte Ca.91733]... How is the Feng Shui overall layout to influent the futue products selling for &lt;my&gt; [Boy &amp; Girl dress store] business running in coming [12 years]... ?[: To rent or To buy(m),Feng Shui at : Running Business address(Y9a.se.go),Running Business : Business description and Name(Ss.et),Predict Duration : Select Duration(Tr),Attracting Customer : (C&amp;x),Wealth Luck : (W@w+x)]{AD}&lt;Ss.et/Y9a/C&amp;/Ww@+&gt;80.0.
        /// </summary>
        public static string FengShui005 {
            get {
                return ResourceManager.GetString("FengShui005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to relocate 5 elements(Metal, Wood, Water, Fire, Earth) in Feng Shui overall layout to remove bad effect and to enhence the futue products selling for &lt;my&gt; [Boy &amp; Girl dress store] business running address at [1131 S. Baldwin ave. C-Ste. Arcadia Ca.81007] in coming [12 years] ?[Running Business : Business description and Name(Ss.et),Feng Shui at : Running Business address(Y9a.se.go),Predict Duration : Select Duration(Tr),Attracting Customer : (C&amp;x),Wealth Luck : (W@w+x)]{AD}&lt;Ss.et/Y9a/C&amp;/Ww@+&gt;80.0.
        /// </summary>
        public static string FengShui006 {
            get {
                return ResourceManager.GetString("FengShui006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After relocate 5 elements(Metal, Wood, Water, Fire, Earth) in Feng Shui overall layout at [1131 S. Baldwin ave. C-Ste. Arcadia Ca.81007] ... How &lt;my&gt; expecting the futue products selling for &lt;my&gt; [Boy &amp; Girl dress store] business running be enhenced... How long these Feng Shui effect can be sustained ?[Feng Shui at : Running Business address(Y9a.se.go),Running Business : Business description and Name(Ss.et),Predict Duration : Select Duration(Tr),Attracting Customer : (C&amp;x),Wealth Luck : (W@w+x)]{AR}&lt;Ss.et/Y [rest of string was truncated]&quot;;.
        /// </summary>
        public static string FengShui007 {
            get {
                return ResourceManager.GetString("FengShui007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How is the current Feng Shui overall layout to influent the Enterprise future prosperity for &lt;my&gt; [Samuel Business Consulting Comany] to do Poduct development and sale at [11230 Garvey ave. H-Ste. El Monte Ca.91733] in coming [12 years] ?[Running Enterprise : Enterprise description and Name(Ss.et),Feng Shui at : Running Business address(Y9a.se),Predict Duration : Select Duration(Tr),Wealth Luck : (W&amp;wx),Enterprise Prosperity : (O@x)]{AD}&lt;Ss.et/Y9a.se/W&amp;w/O@&gt;80.0.
        /// </summary>
        public static string FengShui008 {
            get {
                return ResourceManager.GetString("FengShui008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;I&gt; plan to [rent] this office at [11230 Garvey ave. H-Ste. El Monte Ca.91733]... How is the Feng Shui overall layout to influent the Enterprise future prosperity for &lt;my&gt; [Samuel Business Consulting Comany] to do Poduct development and sale in coming [12 years]... ?[: To rent or To buy(m),Feng Shui at : Running Business address(Y9a.se),Running Enterprise : Enterprise description and Name(Ss.et),Predict Duration : Select Duration(Tr),Wealth Luck : (W&amp;wx),Enterprise Prosperity : (O@x)]{AD}&lt;Ss.et/Y9a.se/W&amp;w/O [rest of string was truncated]&quot;;.
        /// </summary>
        public static string FengShui009 {
            get {
                return ResourceManager.GetString("FengShui009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to relocate 5 elements(Metal, Wood, Water, Fire, Earth) in Feng Shui overall layout to remove bad effect and to enhence the Enterprise future prosperity for &lt;my&gt; [Samuel Business Consulting Comany] to do Poduct development and sale at [11230 Garvey ave. H-Ste. El Monte Ca.91733] in coming [12 years] ?[Running Enterprise : Enterprise description and Name(Ss.et),Feng Shui at : Running Enterprise address(Y9a.se.go),Predict Duration : Select Duration(Tr),Wealth Luck : (W&amp;wx),Enterprise Prosperity : (O@x)]{A [rest of string was truncated]&quot;;.
        /// </summary>
        public static string FengShui010 {
            get {
                return ResourceManager.GetString("FengShui010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After relocate 5 elements(Metal, Wood, Water, Fire, Earth) in Feng Shui overall layout at [1131 S. Baldwin ave. C-Ste. Arcadia Ca.81007] ... How &lt;my&gt; expecting the futue prosperity for &lt;my&gt; [Samuel Business Consulting Comany] to do Poduct development and sale be enhenced... How long these Feng Shui effect can be sustained ?[Feng Shui at : Running Business address(Y9a.se.go),Running Enterprise : Enterprise description and Name(Ss.et),Predict Duration : Select Duration(Tr),Wealth Luck : (W&amp;wx),Enterprise Pros [rest of string was truncated]&quot;;.
        /// </summary>
        public static string FengShui011 {
            get {
                return ResourceManager.GetString("FengShui011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to relocate 5 elements(Metal, Wood, Water, Fire, Earth) in Feng Shui overall layout to remove bad effect and to enhence &lt;I&gt; and &lt;my&gt;[wife] to have a [baby without damaging Career] at [11230 Garvey ave. H-Ste. El Monte Ca.91733] living house... ?[: Input Wife or Husband(n),Feng Shui Effects : Select Baby without damaging Career|EqFeng6(Xm)Feng Shui at : Living House address(Y9a.se.go),Have a Baby Luck : (C@x)]{A}&lt;Ss.et/Y9a.se/W&amp;w/O@&gt;80.0.
        /// </summary>
        public static string FengShui012 {
            get {
                return ResourceManager.GetString("FengShui012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FengShui013 {
            get {
                return ResourceManager.GetString("FengShui013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FengShui014 {
            get {
                return ResourceManager.GetString("FengShui014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FengShui015 {
            get {
                return ResourceManager.GetString("FengShui015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FengShui016 {
            get {
                return ResourceManager.GetString("FengShui016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FengShui017 {
            get {
                return ResourceManager.GetString("FengShui017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FengShui018 {
            get {
                return ResourceManager.GetString("FengShui018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FengShui019 {
            get {
                return ResourceManager.GetString("FengShui019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Living Peace/Health : (S@x)]{AD}&lt;Sn@/Xm/Y9a&gt;80.0.
        /// </summary>
        public static string FengShui020 {
            get {
                return ResourceManager.GetString("FengShui020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wealth Luck : (W@wx)]{AD}&lt;Sn/Xm/Y9a/Ww@&gt;80.0.
        /// </summary>
        public static string FengShui021 {
            get {
                return ResourceManager.GetString("FengShui021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Career Luck : (O@f.pfx)]{AD}&lt;Sn/Xm/Y9a/O@f&gt;80.0.
        /// </summary>
        public static string FengShui022 {
            get {
                return ResourceManager.GetString("FengShui022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Living Peace/Health : (S=x),Wealth Luck : (W@wx)]{AD}&lt;Sn=/Y9a/Xm/Ww@&gt;80.0.
        /// </summary>
        public static string FengShui023 {
            get {
                return ResourceManager.GetString("FengShui023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Living Peace/Health : (S=x),Career Luck : (O@fx)]{AD}&lt;Sn=/Xm/Y9a/O@f&gt;80.0.
        /// </summary>
        public static string FengShui024 {
            get {
                return ResourceManager.GetString("FengShui024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wealth Luck : (W@wx),Career Luck : (O@fx)]{AD}&lt;Sn/Xm/Y9a/Ww&amp;/O@f&gt;80.0.
        /// </summary>
        public static string FengShui025 {
            get {
                return ResourceManager.GetString("FengShui025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FengShui026 {
            get {
                return ResourceManager.GetString("FengShui026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Living Peace/Health : (S@x)]{AD}&lt;Sn@/Xm/Y9a&gt;80.0.
        /// </summary>
        public static string FengShui027 {
            get {
                return ResourceManager.GetString("FengShui027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wealth Luck : (W@wx)]{AD}&lt;Sn/Xm/Y9a/Ww@&gt;80.0.
        /// </summary>
        public static string FengShui028 {
            get {
                return ResourceManager.GetString("FengShui028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Career Luck : (O@f.pfx)]{AD}&lt;Sn/Xm/Y9a/O@f&gt;80.0.
        /// </summary>
        public static string FengShui029 {
            get {
                return ResourceManager.GetString("FengShui029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wealth Luck : (W@wx)]{AD}&lt;Sn/Xm/Y9a/Ww@&gt;80.0.
        /// </summary>
        public static string FengShui030 {
            get {
                return ResourceManager.GetString("FengShui030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Career Luck : (O@f.pfx)]{AD}&lt;Sn/Xm/Y9a/O@f&gt;80.0.
        /// </summary>
        public static string FengShui031 {
            get {
                return ResourceManager.GetString("FengShui031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wealth Luck : (W@wx),Career Luck : (O@fx)]{AD}&lt;Sn/Xm/Y9a/Ww&amp;/O@f&gt;80.0.
        /// </summary>
        public static string FengShui032 {
            get {
                return ResourceManager.GetString("FengShui032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FengShui033 {
            get {
                return ResourceManager.GetString("FengShui033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FengShui034 {
            get {
                return ResourceManager.GetString("FengShui034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FengShui035 {
            get {
                return ResourceManager.GetString("FengShui035", resourceCulture);
            }
        }
    }
}
