//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EditDivineEq.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GoodText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GoodText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EditDivineEq.Resources.GoodText", typeof(GoodText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will it safe and peaceful for &lt;me&gt; to go to [cnstruction site] there within next coming [8 hours] ... ?[Location/Area : Leave for Location/Area(Ya),Divine Duration : Select Duration(Tr),Physical safety : (S@x),Unforeseen Event : (X~)]{AR}&lt;S@/Ya/X~&gt;16.0.
        /// </summary>
        public static string Good000 {
            get {
                return ResourceManager.GetString("Good000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can &lt;I&gt; pass through a safe and peaceful outside home house activity without any unexpected accident happening to &lt;me&gt; to damage my physical health Within next coming [1 year]... ?[Divine Duration : Select Duration(Tr),Physical safety : (S@x),Unforeseen Event : (X~)]{AR}&lt;S@/X~&gt;16.0.
        /// </summary>
        public static string Good001 {
            get {
                return ResourceManager.GetString("Good001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can &lt;I&gt; pass through a safe and peaceful in home house living without any unexpected accident happening to &lt;me&gt; Within next coming [1 year]... ?[Divine Duration : Select Duration(Tr),Physical safety : (S@x),Unforeseen Event : (X~)]{AR}&lt;S@/X~&gt;16.0.
        /// </summary>
        public static string Good002 {
            get {
                return ResourceManager.GetString("Good002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How is &lt;my&gt; physical [Cardiovascular system] organ health state within coming [1 year] ... ?[Physical Organ : Select Physical Organ|EqOrgan12(Xu),Divine Duration : Select Duration(Tr),Physical Health : (S@x),Unforeseen Event : (X~)]{AR}&lt;S@/Xu~&gt;16.0.
        /// </summary>
        public static string Good003 {
            get {
                return ResourceManager.GetString("Good003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just get lost.... (his) Cell phone is not answering... somewhere in [Nevada Carson desert on Free High Way 80]... Having not been found for [several hours]... How is [Mr.X name] right now... Is (he) still safe and alive ?[Location/Area : Area / Location(a),Divine Duration : Select Duration(Tr),Mr. : Substitute for person&apos;s X name(S@sn),Life safety : (S@nsx),Unforeseen Event : (X~)]{AR}&lt;S@sn/X~&gt;8.0.
        /// </summary>
        public static string Good004 {
            get {
                return ResourceManager.GetString("Good004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing somewhere in [Yellow Stone park]... Having not been found for [several days]... How is [Mr.X name] right now... Is (he) still safe/alive ?[Location : Area Location(a),Divine Duration : Select Duration(Tr),Mr. : Substitute for person&apos;s X name(S@sn),Life safety : (S@x),Unforeseen Event : (X~)]{AR}&lt;S@sn/X~&gt;8.0.
        /// </summary>
        public static string Good005 {
            get {
                return ResourceManager.GetString("Good005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Good006 {
            get {
                return ResourceManager.GetString("Good006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Good007 {
            get {
                return ResourceManager.GetString("Good007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Good008 {
            get {
                return ResourceManager.GetString("Good008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ Check Action !? ].
        /// </summary>
        public static string Good070 {
            get {
                return ResourceManager.GetString("Good070", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If &lt;I&gt; decide to work in this [Software Dept. in Alga Company] as a [entry level Software Engr.]... How is the career/job security in coming [1 year]...?[Work in : Company name(Ye.et),Work as a : Job/Profession Description (O@f.pf),Divine Duration : Select Duration(Tr),Supervisor/Colleagues : (Mx),My adaptivity/life peace : (Jx),Friendly working evronment : (Kx),Job Security : (O@f.pfx)]{AD}&lt;Sn/Mn/Ye/O@f/J/K&gt;32.0.
        /// </summary>
        public static string Good100 {
            get {
                return ResourceManager.GetString("Good100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How is the auspicious and ominious prospect regarding the wealth luck for &lt;me&gt; to open &lt;my&gt; [Construction Material suply business] at this [5821 Temple City Blvd. Temple City CA.91780] in coming [3 years]...?[Running Business : Input Business category/description(S=.et),Location at : Input adress/location(Ya),Divine Duration : Select Duration(Tr),Money/Revenue Earnings : (W@wh+x),Product Quality/Merit : (Jx.go),Marketing Costomer Potentiality : (Kx.ct)]{AD}&lt;S=.et/Ya/W@wh+/J/K&gt;48.0 .
        /// </summary>
        public static string Good101 {
            get {
                return ResourceManager.GetString("Good101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How it will be... If &lt;I&gt; [refuse to corporate with] [Mr.] [Xname] with regard to [this design project]... What will bring about to &lt;my&gt; [accounting assistant] Job security ?[ : Intend action, : Select Miss / Mrs. or Mr. for named X person(yn!),Conflicter : Conflicter/Mr.X name(Yn!), : Describe conflicting thing(Mm),Job/Career : Input Job description(O@f.pf),Changing Matter To Me : (S=x),Job Security : (O@fx)]{AD}&lt;S=n/Mm/Yn!/O@f&gt;32.0.
        /// </summary>
        public static string Good102 {
            get {
                return ResourceManager.GetString("Good102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If &lt;I&gt; demand to [increase current monthly salary by 20%]... How will &lt;my&gt; [Boss] [X name] response... What will bring about regarding &lt;my&gt; [job] working in [Software Dept. in Alga Company] ...?[Intend Action : What you intend to do,: Input Manager or Boss or Director(jn),Boss : Influencer / X name(Mn),Career/Job : Describe Profession/Position(Of.pf),Orgazination/Company : Describe Orgazination(Ye.et),Job Security : (O@f.pfx)]{AD}&lt;Sn/Mn/Ye/O@f&gt;32.0.
        /// </summary>
        public static string Good103 {
            get {
                return ResourceManager.GetString("Good103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The [blizzard is so heavy]... If &lt;I&gt; [keep to drive car further]... How it will be... Any bad thing unexpected  ahead... ?[Unknown/Danger : Describe the critial situation(m),Intend To Do : Describe intend to do(X),Life safety : (S@x)]{AD}&lt;S@n/X~&gt;48.0.
        /// </summary>
        public static string Good104 {
            get {
                return ResourceManager.GetString("Good104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [On this heavily snowing slippy I-25 Free high way] .... Can &lt;I&gt; [keep driving car forward on this way further]... Is it safe ?[Critial situation : Discribe the critial situation(m),Intend To Do : What intend to do(X),Life safety : (S@x)]{AD}&lt;S@n/X~&gt;48.0.
        /// </summary>
        public static string Good105 {
            get {
                return ResourceManager.GetString("Good105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If &lt;I&gt; [detour to 210 W. high way]... How it will be... Is it safe for &lt;me&gt; to do action further... ?[Intend Action : Intend action(Ym),Unknown/Danger : (X),Life Safety : (S@x),Changing Matter : (X~)]{AD}&lt;S@n/Ym/X~&gt;48.0.
        /// </summary>
        public static string Good106 {
            get {
                return ResourceManager.GetString("Good106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If &lt;I&gt; take this [NW Flight No25 air plane] from [Los Angle]... Wll it be safe and peaceful for &lt;me&gt; to reach [Chicago] on [Oct.26 morning]... ?[Transportation : Describe your transportation(Mg.tp),From city : From city(Ja),To city : Your destination(Ya), : Input departure date(t), Weather/Climate : (P~x),Life Safety : (S@x)]{AD}&lt;S@n/Ja/Mg/Ya/P~&gt;48.0.
        /// </summary>
        public static string Good107 {
            get {
                return ResourceManager.GetString("Good107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How &lt;my&gt; life health will be effected by the Feng Shui effect at [256 Mountain View Blvd. El Monte CA.]... if &lt;I&gt; move in there as my living house in coming [2 years]... ?[Feng Shui at : Living House address(Ya),Predict Duration :  Select Duration(Tr),Good Health/Living Peace : (S@x))]{AD}&lt;S@n/Ya&gt;48.0.
        /// </summary>
        public static string Good108 {
            get {
                return ResourceManager.GetString("Good108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will it be peaceful and safe for &lt;me&gt; to travel to [North Korea] [in next 2 coming months] ?[Travel Area : Area name(Ya),Predict Traveling Duration :  Select Duration(Tr),Life Safety/Living Peace : (Sn@x)]{AR}&lt;S@n/Ya&gt;48.0.
        /// </summary>
        public static string Good109 {
            get {
                return ResourceManager.GetString("Good109", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will it be peaceful and safe for &lt;me&gt; to study [Civil Engineerin Master] at that [Austrilia Sydney University] for next coming [2 years] ?[Activity : Input Study/Activity(P=m),Study School : School name(Y.sh),Predict activity Duration : Select Duration(Tr),Life Safety/Living Peace : (Sn@x)]{AR}&lt;S@n/Y.sh/P=m&gt;48.0.
        /// </summary>
        public static string Good110 {
            get {
                return ResourceManager.GetString("Good110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will it be peaceful and safe for &lt;me&gt; go to that [military mission] in [Iran] in next coming [6 Months] ?[ : Describe Activity(m),Region/Area : Region/Area(Ya),Predict Activity Duration :  Select Duration(Tr),Life Safety/Living Peace : (Sn@x)]{AR}&lt;S@n/Ya&gt;48.0.
        /// </summary>
        public static string Good111 {
            get {
                return ResourceManager.GetString("Good111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will it be peaceful and safe for &lt;me&gt; to [run business] at [North Africa] in next coming [2 years] ?[ : Describe Activity(m),Region/Area : Activity In Region/Area(Ya),Predict Staying Duration : Select Duration(Tr),Life Safety/Living Peace : (Sn@x)]{AR}&lt;S@n/Ya&gt;48.0.
        /// </summary>
        public static string Good112 {
            get {
                return ResourceManager.GetString("Good112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suffering [Osteoporosis]... Will there be an accident... if &lt;I&gt; [carry that weight luggage to travel] in coming [20 days] ?[Watch Sickness : Describe weakness(Ok~), : Discribe Activity(Ym),Predict Activity Duration :  Select Duration(Tr),Life Safety/Good Health : (S@x)]{AR}&lt;S@n/Ym/Ok~&gt;48.0.
        /// </summary>
        public static string Good113 {
            get {
                return ResourceManager.GetString("Good113", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;I&gt; have been suffering [high blood pressure]... Is there any accident risk ahead of &lt;me&gt; in coming [12 days] ?[Watching Sickness : Describe watching weakness(Ok~),Predicting Duration :  Select Duration(Tr),Life/Health : (Sn@x)]{AR}&lt;S@n/Ok~&gt;48.0.
        /// </summary>
        public static string Good114 {
            get {
                return ResourceManager.GetString("Good114", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will the customized targeting theray implemented by [Thomas] Doctor&apos;s prescription Can effectively cure &lt;my&gt; [lung cancer] and save life in coming [one year] ?[Doctor : Input Doctor&apos;s Name(Y.dtn),Sickness : Sick Name(O.sk),Predicting Duration :  Select Predicting Duration(Tr),Life Safety/Health Recovery : (Sn@x)]{AR}&lt;Sn@/Y.dtn/O.sk&gt;48.0.
        /// </summary>
        public static string Good115 {
            get {
                return ResourceManager.GetString("Good115", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Good116 {
            get {
                return ResourceManager.GetString("Good116", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Good117 {
            get {
                return ResourceManager.GetString("Good117", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Good118 {
            get {
                return ResourceManager.GetString("Good118", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Sick / Life State !?].
        /// </summary>
        public static string Good130 {
            get {
                return ResourceManager.GetString("Good130", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rescently just Having found... &lt;I&gt; get [serious diabetes]... How fatal/serious it will be aganist &lt;my&gt; life in coming [1 year]... Should &lt;I&gt; take any medicine ?[Sickness : Discribe sick name and state(Ok~.sk),Predict Duration : Select within Duration(Tr),Life Safety/Good Health : (S@x),Medicine : (C=.mdmx)]{AR}&lt;S@n/Ok~/Cm=&gt;60.
        /// </summary>
        public static string Good200 {
            get {
                return ResourceManager.GetString("Good200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Being [in ICU] for [several hours/days]... How is [Mr.X name]&apos;s vital sign going on...  Will (he) revive self conscious in coming [1 week]... when ?[ : Describe critial situation, : Input duration days/hours(t),Mr. : Substitute for person&apos;s X name(Ssn!),Predicting Duration : Expect revive within(Tr),Life Safety/Revive Concious : (S@x)]{AR}&lt;S@sn&gt;60.
        /// </summary>
        public static string Good201 {
            get {
                return ResourceManager.GetString("Good201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just Currently sustaining [in ICU unconciously]... How [Mr.X name]&apos;s life will be... Will (he) [wake up and surrive] in coming next [24 hours]... when ?[ : Discribe critial situation(m),: Substitute for person&apos;s X name(S@sn!), : Discribe expecting state(m),Predict Duration : Select within Duration(Tr),Life Safety/Revive Concious : (S@snx)]{AR}&lt;S@sn&gt;60.
        /// </summary>
        public static string Good202 {
            get {
                return ResourceManager.GetString("Good202", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently has been sustaining [in coma state] for [several days]... How [Mr.X name]&apos;s life will be... will (he) revive conscious... when ?[Discribe dangerous state,Specify duration,: Substitute for person&apos;s X name(Ssn!),Predict Duration : Select within Duration(Tr),Life Safety/Revive Concious : (S@x)]{AR}&lt;S@sn&gt;60.
        /// </summary>
        public static string Good203 {
            get {
                return ResourceManager.GetString("Good203", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Being seriously [wounded at head]... How [Mr.X name]&apos;s life will be... Will (he) through this [medical treatment] and recover (his) health ... ?[Wound : Wounded description(Ok~.sk),: Substitute for person&apos;s X name(Ssn!),Therapy : Name for therapy(C&amp;),Life Safety/Revive Concious : (S@x)]{AD}&lt;S@sn/Ok~/C&amp;&gt;60.
        /// </summary>
        public static string Good204 {
            get {
                return ResourceManager.GetString("Good204", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Having been suffering [sciatic nervous pain]... Can &lt;I&gt; safely go through this [sciatic surgery] to get ride of this sickness ?[Sickness : Discribe sick name and state(Ok~.sk),Surgery : Surgery location / name(Y.sg),Life Safety/Recover Health : (S@x)]{AD}&lt;S@n/Y.sg/Ok~&gt;60.
        /// </summary>
        public static string Good205 {
            get {
                return ResourceManager.GetString("Good205", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready for this heavy [heart surgery]... Shall &lt;I&gt; recover &lt;my&gt; life health through this surgery ?[Surgery : Surgery name(Y~.sg),Life Safety/Recover Health : (S@x)]{AD}&lt;S@n/Y&gt;60.
        /// </summary>
        public static string Good206 {
            get {
                return ResourceManager.GetString("Good206", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Being worry about the past [stomach cancer]....How &lt;my&gt; health will be within [this year]... Will it bring about again ?[Sickness : Sick name(Ok~),Predicting Duration :  Select within Duration(Tr),Unknown/Danger : (X~x),Life Safety/Good Health : (S@x)]{AR}&lt;S@n/Ok/X~&gt;48.0.
        /// </summary>
        public static string Good207 {
            get {
                return ResourceManager.GetString("Good207", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will this [stomach surgery] to be conducted by doctor [Karen Wang] in the [Methodist Teaching] hospital recover &lt;my&gt; health on [March 28]... ?[Surgery : Input Surgery Name(C.sg),Doctor : Input Doctor&apos;s Name(Yn.dt),Hospital : Input Hosital Name(M.hp),Date : Input Surgery Date(t),Life Safety/Recover Health : (S@x)]{AD}&lt;S@n/M/Yn&gt;48.0.
        /// </summary>
        public static string Good208 {
            get {
                return ResourceManager.GetString("Good208", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will &lt;my&gt; life be rescued through this [Stomach surgery] ?[Surgery : Sugery name(Y.sgg),Life Safety/Recover Health : (S@x),Changing Matter : (X~)]{AD}&lt;S@n/Yg/X~&gt;60.
        /// </summary>
        public static string Good209 {
            get {
                return ResourceManager.GetString("Good209", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can &lt;my&gt; artificial pregant [embryo] surrive and securely grow up in &lt;my&gt; body through the assistance from [Mr.] [X name] doctor ?[ : Select Baby or Embryo|EqBaby2(C@n~),Doctor : Input Doctor&apos;s Name(Yn!.dt),Life Safety/Good Health : (C@x)]{AD}&lt;Sn/Yn!.dt/C@n&gt;48.0.
        /// </summary>
        public static string Good210 {
            get {
                return ResourceManager.GetString("Good210", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How is the effectiveness of current [lung cancer] therapy being processed under the [x Name] dooctor&apos;s prescription...Any on going positive progress... Can &lt;I&gt; recover health in coiming [6 months] ?[Sickness : Sick Name(O.sk),Doctor : Input Doctor&apos;s Name(Y.dt),Predicting Duration :  Select Duration(Tr),Life Safety/Health Recovery : (Sn@x)]{AD}&lt;S@n/Y/O&gt;48.0.
        /// </summary>
        public static string Good211 {
            get {
                return ResourceManager.GetString("Good211", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Good212 {
            get {
                return ResourceManager.GetString("Good212", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Good213 {
            get {
                return ResourceManager.GetString("Good213", resourceCulture);
            }
        }
    }
}
