//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EditDivineEq.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HouseText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HouseText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EditDivineEq.Resources.HouseText", typeof(HouseText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the effect of wealth and health luck for (me) about currently living in [256 S. Baldwin Blvd. Arcadia CA.] house ?[House Address(YA)]{AO}&lt;S&amp;/Y/W@&gt;100.
        /// </summary>
        public static string House000 {
            get {
                return ResourceManager.GetString("House000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What will be the effect of wealth and career luck for (me) to live in [630 W. Huntington Dr. 228 Apt. Arcadia CA.] house ?[House Address(Y)]/S/Y/W&amp;/O@/200.
        /// </summary>
        public static string House001 {
            get {
                return ResourceManager.GetString("House001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the business developable luck/carriage for (me) to move in this [256 W. FootHill Blvd. Monrovia CA] office where (I) want to start (my) business ?[Office Address(Y)]/S/Y/O@/200.
        /// </summary>
        public static string House002 {
            get {
                return ResourceManager.GetString("House002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What will be the wealth luck for (me) to run business in [346 S. Rosemead E. Pasadena CA.] storefront ?[Frontstore Address(Y)]/S/Y/W@/200.
        /// </summary>
        public static string House003 {
            get {
                return ResourceManager.GetString("House003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What will be wealth luck for (me) to run business in [Pasadena county] region ?[County/Region Name(Y)]/S/Y/W@/200.
        /// </summary>
        public static string House004 {
            get {
                return ResourceManager.GetString("House004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will [2Level 400 S. Baldwin Ave. Westfield Arcadia CA.] booth well exhibit product and invoke customers to bring profits for (my) business ?[Booth Address(Y)]/S/Y/C/W@/200.
        /// </summary>
        public static string House005 {
            get {
                return ResourceManager.GetString("House005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How is the currently pricing state regarding (my) real estate at [245 E. Colorado Blvd. Lamada Park CA.] in market ?[Real Estate Address(Y)]/S/Y/C/W@/200.
        /// </summary>
        public static string House006 {
            get {
                return ResourceManager.GetString("House006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How is the [$500,000.0] appraisal pricing state for (my) real estate at [256 Longden Blvd. San Marino CA.] in current market ?[Appraisal Price(W),Real Estate Address(Y)]/S/Y/C/W@/200.
        /// </summary>
        public static string House007 {
            get {
                return ResourceManager.GetString("House007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string House008 {
            get {
                return ResourceManager.GetString("House008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string House009 {
            get {
                return ResourceManager.GetString("House009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To buy.
        /// </summary>
        public static string House020 {
            get {
                return ResourceManager.GetString("House020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will it bring wealth for (me) to buy [256 E. MockingBird Ln Lackwood Tx.] land... How is the future pricing prospect of it in coming one more year ?[Land Location](Y)/S/Y/C/W@/200.
        /// </summary>
        public static string House100 {
            get {
                return ResourceManager.GetString("House100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (I) intend to invest more than one year... What is the wealth prospect for (me) to buy [56 N. Buckner Blvd. Casa Linda Tx.] real estate ?[Real Estate Address(Y)]/S/Y/C/W@/200.
        /// </summary>
        public static string House101 {
            get {
                return ResourceManager.GetString("House101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How the future price will be for [45 Grove St. Greenwinch Village NY.] real estate which (I) intend to invest more than one year ?[Real Estate  Address(Y)]/S/Y/C/W@/200.
        /// </summary>
        public static string House102 {
            get {
                return ResourceManager.GetString("House102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (I) have already owned this [66 W. Southmore Ave. Pasadena Huston TX] house for one more year... Will the price of it rise up ?[House  Address(Y)]/S/Y/C/W@/200.
        /// </summary>
        public static string House103 {
            get {
                return ResourceManager.GetString("House103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How is the futute price evolving for (my) current one more year owning [66 Navigation Blvd. Second Ward Huston TX.] real estate in coming next year ?[Real Estate  Address(Y)]/S/Y/C/W@/200.
        /// </summary>
        public static string House104 {
            get {
                return ResourceManager.GetString("House104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can (I) buy [56 E. 6th Ave. Aurora Co.] real estate at [$560,000.0] [cost price] to earn profit after one year ?[Real Estate Address(Y),Bit Price Quantity(W),Describe Pricing Method]/S/Y/C/W@/200.
        /// </summary>
        public static string House105 {
            get {
                return ResourceManager.GetString("House105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it profitable for (me) to buy [126 W. Oxford Ave. Eaglewood Denver CO.] real estate at [$460,000.0] [appraisal price]... Will it&apos;s price still rise up after one year ?[Real Estate Address(Y),Bit Price Quantity(W),Describe Pricing Method]/S/Y/C/W@/200.
        /// </summary>
        public static string House106 {
            get {
                return ResourceManager.GetString("House106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can (I) persist my [$800,000.0] offering price... to buy out that [66 E. 8Th Ave. Thronton Denver Co.] real estate from [Owner Mr. X] ?[Offering Price(W),Real Estate Address,Owner Name(Y)]/S/Y/W@/200.
        /// </summary>
        public static string House107 {
            get {
                return ResourceManager.GetString("House107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can (I) persist my [$660,000.0] offering price... Will the owner [Mr. X] still want to sell that [256 Longden Blvd. San Marino CA.] real estate to (me) through [Mr. Y] agent ?[Offering Price(W),Owner Name(Y),Real Estate Address,Agent/Mr. Y Name]/S/M/Y/W@/200.
        /// </summary>
        public static string House108 {
            get {
                return ResourceManager.GetString("House108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How much is the adjustment aganist [$660,000.0] appraisal price for (me) to buy out that [346 S. Rosemead E. Pasadena CA.] real estate ?S/Y[Real Estate Address]/C/W{Appraisal Price}@/200.
        /// </summary>
        public static string House109 {
            get {
                return ResourceManager.GetString("House109", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will [Mr. X] customer buy this [256 E. MockingBird Ln Lackwood Tx.] real estate at my client [Mr. Y]&apos;s [$680,000.0] target price ?[Client/Mr.X Name,Real Estate Address(Y),Customer/Mr.Y Name,Target Price(W)]/Ss/M/Y/W@/200.
        /// </summary>
        public static string House110 {
            get {
                return ResourceManager.GetString("House110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string House111 {
            get {
                return ResourceManager.GetString("House111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string House112 {
            get {
                return ResourceManager.GetString("House112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string House113 {
            get {
                return ResourceManager.GetString("House113", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string House114 {
            get {
                return ResourceManager.GetString("House114", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To sell.
        /// </summary>
        public static string House130 {
            get {
                return ResourceManager.GetString("House130", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will it be profitable for (me) to sell my [126 W. Oxford Ave. Eaglewood Denver CO.] real estate which (I) have owned one more year... now ?[Real Estate Address(Y)]/S/Y/C/W@/200.
        /// </summary>
        public static string House200 {
            get {
                return ResourceManager.GetString("House200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When is the most profitalbe timing for (me) to sell (my) owning one more year [256 Longden Blvd. San Marino CA.] real estate ?[Real Estate Address(Y)]/S/Y/C/W@/200.
        /// </summary>
        public static string House201 {
            get {
                return ResourceManager.GetString("House201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can (I) have my owning one year more [256 E. MockingBird Ln Lackwood Tx.] real estate to sell out above [$660,000.0] appraisal price within the [Mr. X] agent&apos;s contracting period of [3 months] ?[Real Estate Address(Y),Appraisal Price,Agent/Mr. X Name,Contract Period]/S/M/Y/C/W@/200.
        /// </summary>
        public static string House202 {
            get {
                return ResourceManager.GetString("House202", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If (I) persist the target [$660,000.0] price... not including [Mr. X] agent fee... Will [Mr. Y] Buyer still want to buy my [256 E. MockingBird Ln Lackwood Tx.] real estate ?[Target Price(W),Buyer Name,Mr.X/Agent Name,Real Estate Address(Y)]/S/M/Y/C/W@/200.
        /// </summary>
        public static string House203 {
            get {
                return ResourceManager.GetString("House203", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can (I) have (my) owning one year more [56 N. Buckner Blvd. Casa Linda Tx.] real estate to be sold out at [$880,000.0] target priece within [3 months] ?[Real Estate Address(Y),Target Price(W),Sale Duration]/S/Y/C/W@/200.
        /// </summary>
        public static string House204 {
            get {
                return ResourceManager.GetString("House204", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I mark my [256 E. MockingBird Ln Lackwood Tx.] real estate at [$880,000.0] price... How the market sale will be... Is this price too low ?[Real Estate Address(Y),Target Price(W)]/S/Y/C/W@/200.
        /// </summary>
        public static string House205 {
            get {
                return ResourceManager.GetString("House205", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seveal price offering below the [$460,000.0] appraisal price... sale is about to closed... Is there still some higher offering I can wait to sell my [256 E. MockingBird Ln Lackwood Tx.] real estate at my [$500,000.0] target price ?[Appraisal Price(W),Real Estate Address(Y),Target Price]/S/Y/C/W@/200.
        /// </summary>
        public static string House206 {
            get {
                return ResourceManager.GetString("House206", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How the suggesting [$560,000.0] appraisal price from [Mr. X] agent will be... Can I still persist my [$600,000.0] target higher price to have my [245 E. Colorado Blvd. Lamada Park CA.] real estate salable in market ?[Apprasal Price,Mr.X/Agent Name,Target Price,Real Estate Address(Y)]/S/M/Y/C/W@/200.
        /// </summary>
        public static string House207 {
            get {
                return ResourceManager.GetString("House207", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If (I) mark my [$800,000.0] target price higher than the [$750,000.0] appraisal price... Will my [456 W. Rooselvelt Rd. University Village IL.] real estate still salable through &lt;Mr. X&gt; agent ?[Target Price,Apprasal Price,Real Estate Address(Y),Mr.X/Agent Name]/S/M/Y/C/W@/200.
        /// </summary>
        public static string House208 {
            get {
                return ResourceManager.GetString("House208", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will [Mr. X] owner sell his [256 E. MockingBird Ln Lackwood Tx.] real estate to my customer [Mr. Y]  at his [$800,000.0] offering price lower than the [$850,000.0] appraisal price ?[Mr. X/Owner(S),Real Estate Address,Mr. Y/Customer Name(Y),Offering Price(W),Apprasal Price]/Ss/Y/W@/200.
        /// </summary>
        public static string House209 {
            get {
                return ResourceManager.GetString("House209", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string House210 {
            get {
                return ResourceManager.GetString("House210", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Rent.
        /// </summary>
        public static string House230 {
            get {
                return ResourceManager.GetString("House230", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can (I) continue to rent this [126 W. Oxford Ave. Eaglewood Denver CO.] real estate from [Mr. X] landlord at this [$2,500.0] amount of rent ?[Real Estate Address,Landlord Nam(Y),Rent Quantity(W)]/S/Y/P@/200.
        /// </summary>
        public static string House301 {
            get {
                return ResourceManager.GetString("House301", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If (I) continue to rent [56 N. Buckner Blvd. Casa Linda Tx.] real estate, Will [Mr. X] landlord increase my rent... How many % will be increased ?[Real Estate Address,Landlord Name(Y)]/S/Y/W/P@/200.
        /// </summary>
        public static string House302 {
            get {
                return ResourceManager.GetString("House302", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can (I) continue to pay the same [$2,500.0] amount of rent to rent [256 Longden Blvd. San Marino CA.] real estate from [Mr. X] landlord ?[Rent Quantity,Real Estate Address,Landlord Name(Y)]/S/Y//P/200.
        /// </summary>
        public static string House303 {
            get {
                return ResourceManager.GetString("House303", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is there someone willing to pay higher rent than (my) current [$2,600.0] rent to rent this [256 S. Baldwin Blvd. Arcadia CA.] real estate from [Mr. X] landlord ?S/Y[Rent Quantity(W),Real Estate Address,Landlord Name(Y)]/S/Y/W@/X/200.
        /// </summary>
        public static string House304 {
            get {
                return ResourceManager.GetString("House304", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string House305 {
            get {
                return ResourceManager.GetString("House305", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string House306 {
            get {
                return ResourceManager.GetString("House306", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string House307 {
            get {
                return ResourceManager.GetString("House307", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Lease.
        /// </summary>
        public static string House320 {
            get {
                return ResourceManager.GetString("House320", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will [Mr. X] tenant rent my [240 Geary Blvd. Inner Richmond Sanfancisco CA.]  real estate at my [$4,500.0/Month] target price ?[Mr.X/Tenant Name, Real Estate Address,Rent /Month]/S/Y/W/200.
        /// </summary>
        public static string House400 {
            get {
                return ResourceManager.GetString("House400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can I persist the rent at [$2,600.0/month] for [260 Gaston Ave. Munger Place Dallas Tx.] my real estate in current market to be leased ?[Rent/Month(W),Real Estate Address(Y)]/S/Y/X@/200.
        /// </summary>
        public static string House401 {
            get {
                return ResourceManager.GetString("House401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When can (I) have my [256 Longden Blvd. San Marino CA.] real estate to be leasted at this [$3,600.0/month] rent ?[Real Estate Address(Y),Rent/Month]/S/Y/W@/200.
        /// </summary>
        public static string House402 {
            get {
                return ResourceManager.GetString("House402", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After [Mr. X] tenant visit my [126 W. Oxford Ave. Eaglewood Denver CO.] real estate ... Will he rent my real estate at [$2,600.0/month] ?[Tenant Name(Y),Real Estate Address,Rent/Month]/S/Y/W@/200.
        /// </summary>
        public static string House403 {
            get {
                return ResourceManager.GetString("House403", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string House404 {
            get {
                return ResourceManager.GetString("House404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string House405 {
            get {
                return ResourceManager.GetString("House405", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent.
        /// </summary>
        public static string House420 {
            get {
                return ResourceManager.GetString("House420", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can (Mr. X) real estate agent sell (my) [346 S. Rosemead Blvd. Pasadena CA.] real estate at highest price ?[Mr. X/Agent Name,Real Estate Address(Y)]/S/M/Y/C/W@/200.
        /// </summary>
        public static string House500 {
            get {
                return ResourceManager.GetString("House500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will [Mr. X] real estate agent can sell my [256 Longden Blvd. San Marino CA.] real estate above (my) [$680,000.0] target price without agent fee ?[Mr. X/Agent Name,Real Estate Address(Y),Target Price(W)]/S/M/Y/W@/200.
        /// </summary>
        public static string House501 {
            get {
                return ResourceManager.GetString("House501", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will (Mr. X) real estate agent sell my [66 W. Southmore Ave. Pasadena Huston Tx.] real estate above the [$980,000.0] appraisal price  without agent fee within the sale contract duration ?[Mr. X/Agent Name,Real Estate Address(Y),Appraisal Price(W)]/S/M/Y/W@/200.
        /// </summary>
        public static string House502 {
            get {
                return ResourceManager.GetString("House502", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string House503 {
            get {
                return ResourceManager.GetString("House503", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string House504 {
            get {
                return ResourceManager.GetString("House504", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string House505 {
            get {
                return ResourceManager.GetString("House505", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to architectural layout plan.
        /// </summary>
        public static string House520 {
            get {
                return ResourceManager.GetString("House520", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string House600 {
            get {
                return ResourceManager.GetString("House600", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string House601 {
            get {
                return ResourceManager.GetString("House601", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string House602 {
            get {
                return ResourceManager.GetString("House602", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string House603 {
            get {
                return ResourceManager.GetString("House603", resourceCulture);
            }
        }
    }
}
