//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EditDivineEq.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RomanceText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RomanceText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EditDivineEq.Resources.RomanceText", typeof(RomanceText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If &lt;I&gt; invite [Miss] [Xname] a date [to go dancing party] with &lt;me&gt; on this coming [Friday evening]... Will (she) come ?[: Select Miss / Mrs. or Mr. for named X person(yn!),Miss : Invite MissX&apos;s or Mr&apos;s Name(Yn!),: Describe activity(m),: Specify the activity date(t),Being with me : (Y!@x)]{O}&lt;Sn/Y@n!&gt;8.0.
        /// </summary>
        public static string Romance000 {
            get {
                return ResourceManager.GetString("Romance000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will [Miss] [Xname] accept a date with &lt;me&gt; alone to go [campus rock and roll music concert] in [next Saturday evening] ?[: Select Miss / Mrs. or Mr. for named X person(yn!),Miss : Invite MissX&apos;s or Mr&apos;s Name(Yn!),: Describe activity(m),Specify the activity date(t),Being with me : (Y!@x)]{O}&lt;Sn/Y@n!&gt;8.0.
        /// </summary>
        public static string Romance001 {
            get {
                return ResourceManager.GetString("Romance001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just rescently only acquaint each other... Is [Miss] [Xname] willing to join &lt;me&gt; [to have BBQ] with &lt;my&gt; [family] in coming [this Saturday afternoon] ?[: Select Miss / Mrs. or Mr. for named X person(yn!),Miss : Invite MissX&apos;s or Mr&apos;s Name(Yn!),: Describe activity(m),Accompaning with : Participants(Mn),Specify the activity date(t),Being with me : (Y!@x)]{O}&lt;Sn/Mn/Y@n!&gt;8.0.
        /// </summary>
        public static string Romance002 {
            get {
                return ResourceManager.GetString("Romance002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Her) cell phone is not answering... Is [Miss] [Xname] on (her) way coming to date with &lt;me&gt; now ?[: Select Miss / Mrs. or Mr. for named X person(yn!),Miss : Date MissX&apos;s or Mr&apos;s Name(Yn!),Being with me : (Y!@x)]{O}&lt;Sn/Y@n!&gt;8.0.
        /// </summary>
        public static string Romance003 {
            get {
                return ResourceManager.GetString("Romance003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Mr.] [Xname] just being introuced by [sister in law Mrs. A]... Will (he) invite &lt;me&gt; alone to date with (him) in next coming [3 months]... When ?[: Select Miss / Mrs. or Mr. for named X person(yn!),Mr. : Mr.X/boy&apos;s name who invite me(Yn!),Introduced by : Introducer&apos;s Name(Mn),Predict Duration : Select Duration(Tr),Being with me : (Y!@x)]{OR}&lt;Sn/Mn/Y@n!&gt;8.0.
        /// </summary>
        public static string Romance004 {
            get {
                return ResourceManager.GetString("Romance004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Having been acquainting for a while... Will [Mr.] [Xname] invite &lt;me&gt; alone to date with (him) in next coming [3 months]... When ?[: Select Miss / Mrs. or Mr. for named X person(yn!),Mr. : Mr.X or Miss&apos;s Name who invite me(Yn!),Predict Duration : Select Duration(Tr),Being with me : (Y!@x)]{OR}&lt;Sn/Y@n!&gt;8.0.
        /// </summary>
        public static string Romance005 {
            get {
                return ResourceManager.GetString("Romance005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Romance006 {
            get {
                return ResourceManager.GetString("Romance006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Romance007 {
            get {
                return ResourceManager.GetString("Romance007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Romance008 {
            get {
                return ResourceManager.GetString("Romance008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;I&gt; sustituted by diviner in person.
        /// </summary>
        public static string Romance009 {
            get {
                return ResourceManager.GetString("Romance009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (he)/(his)/(him) replaced by  (she)/(her)/(), (W@!) elaced y (O@).
        /// </summary>
        public static string Romance010 {
            get {
                return ResourceManager.GetString("Romance010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .sm girl/bo  wife/husand friend.
        /// </summary>
        public static string Romance011 {
            get {
                return ResourceManager.GetString("Romance011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Romance012 {
            get {
                return ResourceManager.GetString("Romance012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Romance013 {
            get {
                return ResourceManager.GetString("Romance013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Romance.
        /// </summary>
        public static string Romance030 {
            get {
                return ResourceManager.GetString("Romance030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just being introuced by [sister in law Mrs. A]... How does [Miss] [Xname] be impressed about &lt;me&gt;... Will the romance occur to &lt;us&gt;... When ?[Introducer : Introducer&apos;s name(Mn),: Select Miss / Mrs. or Mr. for named X person(yn!.sm),Miss : Introuced MissX name for X person(Yn!.sm),Predict Duration : Select Duration(Tr),My Expect : (S@x),Be impressed about me : (Y=x)]{F}&lt;S@n/Mn/Y=n!&gt;24.0.
        /// </summary>
        public static string Romance100 {
            get {
                return ResourceManager.GetString("Romance100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just come upon with each other in [LoveSpark date club]... Will the love of romance happen to &lt;me&gt; and [Miss] [Xname] to get together ever since... When ?[Meet at : Social club name(M.sl),: Select Miss / Mrs. or Mr. for named X person(yn!),Miss : MissX name for X person(Yn!),Predict Duration : Select Duration(Tr),My Expect  : (S@x),Will Love happen to me : (Y=x)]{F}&lt;S@n/M/Y=n!&gt;24.0.
        /// </summary>
        public static string Romance101 {
            get {
                return ResourceManager.GetString("Romance101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Having been (her) [customer] for a while... Will there be a possibility for &lt;me&gt; to have a romantic relationship with [Miss] [Xname].... When ?[: Describe role of playing with her,: Select Miss / Mrs. or Mr. for named X person(yn!),Miss : MissX name for X person(Yn!),Predict Duration : Select Duration(Tr),My Expect  : (S@x),Will Love happen to me : (Y=x)]{F}&lt;S@n/Y=n!&gt;24.0.
        /// </summary>
        public static string Romance102 {
            get {
                return ResourceManager.GetString("Romance102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Having been acquainting and working together a while... &lt;Am I&gt; attractive to [Miss] [Xname] ... ?[: Select Miss / Mrs. or Mr. for named X person(yn!),Miss : MissX name for X person(Yn!),My Expect  : (S@x),Am I attract to : (Y=x)]{F}&lt;S@n/Y=n!&gt;24.0.
        /// </summary>
        public static string Romance103 {
            get {
                return ResourceManager.GetString("Romance103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Having been acquainting a while... How does [Miss] [Xname] feel about &lt;me&gt;... Is there any possibility... that &lt;we&gt; can be boy-girl friend together... When ?[: Select Miss / Mrs. or Mr. for named X person(yn!),Miss : MissX name for X person(Yn!),Predict Duration : Select Duration(Tr),My Expect  : (S@x),Boy-Girl friend together : (Y=x)]{F}&lt;S@n/Y=n!&gt;24.0.
        /// </summary>
        public static string Romance104 {
            get {
                return ResourceManager.GetString("Romance104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;I&gt; have been very often together with [Miss] [Xname] in this [Social Activity Club]... Will love happen between &lt;us&gt;.... When ?[: Select Miss /Mrs. or Mr. for named X person(yn!),Miss : MissX name for X person(Yn!),Being together in : Social activity club name(M.sl),Predict Duration : Select Duration(Tr),My Expect  : (S@x),Love happen together : (Y=x)]{F}&lt;S@n/M/Y=n!&gt;24.0.
        /// </summary>
        public static string Romance105 {
            get {
                return ResourceManager.GetString("Romance105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How the romantic boy and girl relationship will be evolving between &lt;me&gt; and [Miss] [Xname] in the future.... When ?[: Select Miss or Mr. for named X person(yn!),Miss : MissX name for X person(Yn!),Predict Duration : Select Duration(Tr),My Wish : (S@x),How Love OnGoing : (Y=x)]{F}&lt;S@n/Y=n!&gt;24.0.
        /// </summary>
        public static string Romance106 {
            get {
                return ResourceManager.GetString("Romance106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Since [quarrel].... not being together and phone each other for [several days]... Will there still be a possibility to resume the romantic boy and girl relationship with [Miss] [Xname] for &lt;me&gt; again.... When ?[: describe at thing conflicting(m): Input number of days/weeks(t),: Select Miss or Mr. for named X person(yn!),Miss : MissX name for X person(Yn!),Predict Duration : Select Duration(Tr),My Wish : (S@x),Resume the Love with : (Y=x)]{F}&lt;S@n/Y=n!&gt;24.0.
        /// </summary>
        public static string Romance107 {
            get {
                return ResourceManager.GetString("Romance107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Being not happy at mutual difference/contradictory aganist each other... Does [Miss] [Xname] painfully put efforts to adapt (herself) to &lt;my&gt; individual personality and value preference to deal with &lt;me&gt;... ?[: Select Miss / Mrs. or Mr. for named X person(yn!),Miss : MissX name for X person(Yn!),My Peference : (S@x),Unwilling being with : (Y=x)]{F}&lt;S@n/Y=n!&gt;24.0.
        /// </summary>
        public static string Romance108 {
            get {
                return ResourceManager.GetString("Romance108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Losing connection with  [Miss] [Xname] for several years... &lt;We&gt; are meeting again... Is there possible for &lt;me&gt; to resume romantic boy and girl relationship with (her) again in next coming [3 months]... when ?[: Select Miss / Mrs. or Mr. for Named X person(yn!),Miss : MissX name for X person(Yn!),Predict Duration : Select Duration(Tr),My Wish : (S@x),Resume the Love with : (Y=x)]{FR}&lt;S@n/Y=n!&gt;24.0.
        /// </summary>
        public static string Romance109 {
            get {
                return ResourceManager.GetString("Romance109", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owing to different preference / value choice... Does [Miss] [Xname] still bear &lt;me&gt; in &lt;her&gt; heart of love... Can &lt;we&gt; resume to get together again as &lt;we&gt; used to be in coming next [ 3 months]... When ?[Miss : Select Miss or Mr. for named X person(yn!),: MissX name for X person(Yn!),Predict Duration : Select Duration(Tr),My Wish : (S@x),Resume to get together : (Y=x)]{FR}&lt;S@n/Y=n!&gt;24.0.
        /// </summary>
        public static string Romance110 {
            get {
                return ResourceManager.GetString("Romance110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Having been acquainting for a [1 year] long ... Now can &lt;I&gt; go further to evolve [Miss] [Xname] to be &lt;my&gt; [girl] friend.... When ?[: Input number of years/month(t),: Select Miss / Mrs. or Mr. for named X person(yn!),Miss : Miss / Mrs. name for named X person(Yn!),: Select girl or boy for friend(n!),Predict Duration : Select Duration(Tr),Wife : (W@!x.sm)]{OR}&lt;Sn/Yn!/W@!&gt;24.0.
        /// </summary>
        public static string Romance111 {
            get {
                return ResourceManager.GetString("Romance111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How is the current progress of our romantic ongoing between &lt;me&gt; and [Miss] [Xname] ... Is there any hidden [boy] poacher to compete aganist &lt;me&gt;... ?[: Select Miss / Mrs. or Mr. for named X person(yn!),Miss : MissX name for X person(Yn!),Hidden poacher : Select girl or boy for poacher(Mn!),My feeling : (S@x),How being with me : (Y=x)]{F}&lt;S@n/Mn!/Y=n!/Xn&gt;24.0.
        /// </summary>
        public static string Romance112 {
            get {
                return ResourceManager.GetString("Romance112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How is the compatibility of induvidual personality and value preference between &lt;me&gt; and [Miss] [Xname]... Can &lt;I&gt; actively elvove (her) to be &lt;my&gt; [girl] friend ?[: Select Miss / Mrs.or Mr. for named X person(yn!),Miss : MissX name for X person(Yn!),: Select girl or boy for named X person(n!),My Adaptability : (S@x),Mutual compatibility : (Y=x)]{F}&lt;S@n/Y=n!&gt;24.0.
        /// </summary>
        public static string Romance113 {
            get {
                return ResourceManager.GetString("Romance113", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does [Mr.] [Xname] unconciously conceal (his) real inside individual personal preference and personality to please &lt;my&gt; preference with a view to evolve &lt;me&gt; to become (his) [girl] friend ?[: Select Miss / Mrs. or Mr. for named X person(yn!),Mr. : Mr.X name for X person(Yn!),: Select girl or boy for named X person(n!),My Feeling : (S@x),Real Inside Essentiality : (Y=x)]{F}&lt;S@n/Y=n!&gt;24.0.
        /// </summary>
        public static string Romance114 {
            get {
                return ResourceManager.GetString("Romance114", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Having misunderstanding without communicating with each other for about passing [20 days]... Will my [girl] friend [Miss] [Xname] actively contact &lt;me&gt;... when ?[: Input number of days/weeks(t),: Select boy or girl friend(n!),: Select Miss / Mrs. or Mr. friend(yn!),Miss : MissX name for X person(Yn!),Predict Duration : Select Duration(Tr),Wife : (W@!x.sm)]{OR}&lt;Sn/Yn!/W@n!&gt;60.
        /// </summary>
        public static string Romance115 {
            get {
                return ResourceManager.GetString("Romance115", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owing to [misunderstanding not be able to resolve]... Will the romantic relationship with &lt;my&gt; [girl] friend [Miss] [Xname] break up ?[: Describe misunderstanding(m),: Select boy or girl for friend(n!),: Select Miss / Mrs. or Mr. for friend(yn!),Miss : MissX name for X person(Yn!),Predict Duration : Select Duration(Tr),My feeling : (S@x),Match Feeling : (Y=x)]{F}&lt;S@n/Y=n!&gt;24.0.
        /// </summary>
        public static string Romance116 {
            get {
                return ResourceManager.GetString("Romance116", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does [Miss] [Xname] really bear a sincerely love affection in getting along with &lt;me&gt; as (her) [boy] friend... or (she) mind someone else in (her) heart of love... ?[: Select Miss / Mrs. or Mr. for named X person(yn!),Miss : MissX name for X person(Yn!),: Select girl or boy for named X person(n!),My feeling : (S@x),Match Feeling : (Y=x),Someone Else : (Mnx)]{F}&lt;S@n/Mn/Y=n!&gt;24.0.
        /// </summary>
        public static string Romance117 {
            get {
                return ResourceManager.GetString("Romance117", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is there any intruding hidden competitor who is chasing &lt;my&gt; [girl] friend [Miss] [Xname] ?[: Select boy or girl for friend(n!),: Select Miss / Mrs. or Mr. for friend(yn!),Miss : MissX name for friend(Yn!),My feeling : (S@x),Match Feeling : (Y=x),Hidden Intruder : (Mnx)]{F}&lt;S@n/Mn/Y=n!&gt;24.0 .
        /// </summary>
        public static string Romance118 {
            get {
                return ResourceManager.GetString("Romance118", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;I&gt; just get accquaintance with [Miss] [Xname]... Does (she) currently have any [boy] friend... ?[: Select Miss / Mrs. or Mr. for named X person(yn!),Miss : Mr.X name for X person(Yn!),: Select boy or girl friend(n!),My feeling : (S@x),Match Feeling : (Y=x),Someone Else : (Xnx)]{F}&lt;S@n/Y=n!/Xn&gt;24.0.
        /// </summary>
        public static string Romance119 {
            get {
                return ResourceManager.GetString("Romance119", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does &lt;my&gt; [girl] firend [Miss] [Xname] is still currently geting together with (her) [Ex-boy] friend... behind &lt;me&gt;... ?[: Select boy or girl for named X person(n!),: Select Miss / Mrs. or Mr. for named X person(yn!),Miss : MissX name for X girl(Yn!),: Select Ex-boy or Ex-girl(Xn!),My feeling : (S@x),Match Feeling : (Y=x)]{F}&lt;S@n/Xn!/Y=n!&gt;24.0.
        /// </summary>
        public static string Romance120 {
            get {
                return ResourceManager.GetString("Romance120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Look like... &lt;my&gt; [boy] friend [Mr.] [Xname] is still currently geting together with [Miss] [Yname]... Does &lt;my&gt; [boy] feiend still sincerely love &lt;me&gt; in (his) heart ?[: Select girl or boy for named X person(n!),: Select Miss / Mrs. or Mr. for named X person(yn!),Mr. : Mr.X name for named X person(Yn!),: Select Miss / Mrs. or Mr. for named Y Poacher(jn!),Miss : MissY name for Y Poacher(Mn!),: Select girl or boy for named X person(n!),My feeling : (S@x),Match Feeling : (Y=x),A Poacher : (Mn!x.sm)]{F}&lt;S@n/Mn [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Romance121 {
            get {
                return ResourceManager.GetString("Romance121", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does this just currently acquaint [girl] friend [Miss] [Xname] seduce &lt;me&gt; for a sort of taking advantge from &lt;me&gt;... ?[: Select girl or boy for accquaint friend(n!),: Select Miss / Mrs. or Mr. for accquaint friend(yn!),Miss : MissX Name for Just acquaint friend(Yn!),My Safety/Peace : (S@nx),Changed Yao Action : (Xx)]{A}&lt;Sn@/Y=n!/X&gt;24.0.
        /// </summary>
        public static string Romance122 {
            get {
                return ResourceManager.GetString("Romance122", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is [Mr.] [Xname] a [playboy]... fool &lt;my&gt; sincere affection of love to (him)... ?[: Select Miss / Mrs. or Mr. for playboy(yn!),Mr. : Mr.X name for X Playboy(Yn!),: Select playgirl or playboy(n!),My safety/peace : (S@x),Changed Yao Action : (Xx)]{A}&lt;Sn@/Yn!/X&gt;24.0.
        /// </summary>
        public static string Romance123 {
            get {
                return ResourceManager.GetString("Romance123", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Romance124 {
            get {
                return ResourceManager.GetString("Romance124", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Romance125 {
            get {
                return ResourceManager.GetString("Romance125", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Romance126 {
            get {
                return ResourceManager.GetString("Romance126", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marriage / Romance life.
        /// </summary>
        public static string Romance160 {
            get {
                return ResourceManager.GetString("Romance160", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is there a marriageable match [girl] in &lt;my&gt; life journey... when will (she) show up... When ?[: Select girl or boy(n!),Predict Duration : Select Duration(Tr),Wife : (W@n!+x.sm)]{OR}&lt;Sn/W@n!+&gt;48.0.
        /// </summary>
        public static string Romance200 {
            get {
                return ResourceManager.GetString("Romance200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When shall &lt;I&gt; come upon with a marriageable match [girl] in &lt;my&gt; life... When ?[ : Select girl or boy(n!),Predict Duration : Select Duration(Tr),Wife : (W@!+x.sm)]{OR}&lt;Sn/W@!+&gt;48.0.
        /// </summary>
        public static string Romance201 {
            get {
                return ResourceManager.GetString("Romance201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When shall &lt;I&gt; come upon with a more suitable marriageable match [girl] in next coming [one year] ?[: Select girl or boy(n!),Predict Duration : Specify coming year/months(Tr),Wife : (W@+!x.sm)]{OR}&lt;Sn/W@+!&gt;48.0.
        /// </summary>
        public static string Romance202 {
            get {
                return ResourceManager.GetString("Romance202", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is there a marriageable match [girl] within &lt;my&gt; daily surrounding living and working ?[: Select girl or boy(n!),Predict Duration : Select Duration(Tr),Wife : (W@!x.sm)]{OR}&lt;S/W@!+&gt;48.0.
        /// </summary>
        public static string Romance203 {
            get {
                return ResourceManager.GetString("Romance203", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If &lt;I&gt; join this [Rose Matching Club]... shall &lt;I&gt; come upon with a good marriageable match [girl] in coming [1 month] ?[Meet Marriageable match in : Social activity club name(Y.sl),: Select girl or boy(n!),Predicting duration : Specify coming months(Tr),Wife : (W@!+x.sm)]{OR}&lt;Sn/Y.sl/W@+!&gt;48.0.
        /// </summary>
        public static string Romance204 {
            get {
                return ResourceManager.GetString("Romance204", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;I&gt; have already join [Perfect Match matching club]... Will &lt;I&gt; come upon with a good marriageable match [girl] in next coming [1 month] ?[: Marriage Club Name(Y.sl),: Select girl or boy(n!),Predict Duration : Select Duration(Tr),Wife : (W@!x+.sm)]{OR}&lt;Sn/Y.sl/W@!+&gt;48.0.
        /// </summary>
        public static string Romance205 {
            get {
                return ResourceManager.GetString("Romance205", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;I&gt; decide to leave... Say &quot;Good By&quot; to &lt;my&gt; current [Wife]... Will there still be another new marriagable match [Woman] to show up in &lt;my&gt; futur life journey... When ?[Say &quot;Good By&quot; To : Select you want to leave|EqMatch4(n!),: Select Mary-Match|EqMary4(n!),Predict Duration : Select Duration(Tr),Wife : (W@!+x.sm)]{OR}&lt;Sn/W@!+&gt;48.0.
        /// </summary>
        public static string Romance206 {
            get {
                return ResourceManager.GetString("Romance206", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is [Miss] [Xname] being with &lt;me&gt; in that very gentle way out from (her) real nature personality... or (she) purposely conceals (herself) to behave in that way to please me... What is (her) real heart essentiality ?[: Select Miss / Mrs. or Mr. for named X person(yn!),Miss : MissX/girl&apos;s name(Yn!),My Hapiness : (S@x),How being with me : (Y=x)]{F}&lt;S@n/Y=n!&gt;48.0.
        /// </summary>
        public static string Romance207 {
            get {
                return ResourceManager.GetString("Romance207", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If &lt;I&gt; marry [Miss] [Xname]... How the real reality of mutually being with each other in daily life will be in the future... Will (she) behave as &lt;we&gt; used to be getting together... ?[: Select Miss / Mrs. or Mr. for named X person(yn!),Miss : MissX/girl&apos;s name(Yn!),My Hapiness : (S@x),How being with me : (Y=x)]{F}&lt;S@n/Y=n!&gt;48.0.
        /// </summary>
        public static string Romance208 {
            get {
                return ResourceManager.GetString("Romance208", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can &lt;I&gt; express &lt;my&gt; heart affection feeling to marry [Miss] [Xname] now... How will (she) response...  will (she) promise &lt;my&gt; asking... when ?[: Select Miss or Mr. for named X person(yn!),Miss : MissX/girl&apos;s name(Yn!),Marriage Certificate : (P@x)]{OR}&lt;Sn/Yn!/P@&gt;48.0.
        /// </summary>
        public static string Romance209 {
            get {
                return ResourceManager.GetString("Romance209", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to what is the fate of boy and girl love scenario will be between [Miss] [Xname] and &lt;me&gt; in &lt;my&gt; life journey ?[: Select Miss or Mr. for named X person(yn!),Miss : MissX/girl&apos;s name(Yn!),My Happy life : (S@x),Happy life with me : (Y=x)]{A}&lt;S@n/Y=n!&gt;48.0.
        /// </summary>
        public static string Romance210 {
            get {
                return ResourceManager.GetString("Romance210", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If &lt;I&gt; and [Miss] [Xname] were getting together to marry... How the wealth luck will be for &lt;us&gt; in boy and girl love fate life journey ?[: Select Miss or Mr. for named X person(yn!),Miss : MissX/girl&apos;s name(Yn!),Wealth Luck : (W@wx+)]{A}&lt;Sn/Yn!/W@w+&gt;48.0.
        /// </summary>
        public static string Romance211 {
            get {
                return ResourceManager.GetString("Romance211", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Romance212 {
            get {
                return ResourceManager.GetString("Romance212", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Romance213 {
            get {
                return ResourceManager.GetString("Romance213", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Romance214 {
            get {
                return ResourceManager.GetString("Romance214", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Romance215 {
            get {
                return ResourceManager.GetString("Romance215", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Romance216 {
            get {
                return ResourceManager.GetString("Romance216", resourceCulture);
            }
        }
    }
}
