//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EditDivineEq.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SchoolText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SchoolText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EditDivineEq.Resources.SchoolText", typeof(SchoolText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the future long run... &lt;Am I&gt; adaptable &lt;myself&gt; to study [Graphic design profession]... How this decision will bring about in &lt;my&gt; life career ?[Profession as : Professional category/description(YO@h.pf),My adaptability : (S=x)]{AD}&lt;S=/YOf@h&gt;100.
        /// </summary>
        public static string School000 {
            get {
                return ResourceManager.GetString("School000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the future long term point of view... Will the [Lawyer profrssion] be adaptive to &lt;myself&gt; and bring good earning reward to study ?[Profession as : Professional category(YOf.pf),My adaptability : (S=x),Expect wealth luck : (W@hw+x)]{A}&lt;S=/YOf/W@hw+&gt;100.
        /// </summary>
        public static string School001 {
            get {
                return ResourceManager.GetString("School001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can &lt;I&gt; learn [Accounting] good enough to achieve the competence as a [professional accountant] for &lt;my&gt; future life career ?[Study : Professional course(Yc),Profession as : Professional category(O@fh+.pf),My adaptability : (S=x)]{A}&lt;S=/Y/O@fh+&gt;100.
        /// </summary>
        public static string School002 {
            get {
                return ResourceManager.GetString("School002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the future prospect for &lt;me&gt; to learn the [ballet dancing course] to be a [professional ballet dancer] in &lt;my&gt; future life career... ?[Study : Academic Course category(Y.cr),Profession as : Professional category(O@fh+.pf),My adaptability : (S=x)]{A}&lt;S=/Y/Of@h+&gt;100.
        /// </summary>
        public static string School003 {
            get {
                return ResourceManager.GetString("School003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the future life career prospect regarding to study [Civil Eng.] in the [Sydney University] for &lt;me&gt; to be a [Structural Engr.]... ?[Study : Study course name(Y.cr),Enter : School name(M.sh),Profession as : Professional career category(O@fh+.pf),My adaptability : (S=x)]{A}&lt;S=/M.sh/Y/O@fh+&gt;100.
        /// </summary>
        public static string School004 {
            get {
                return ResourceManager.GetString("School004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the future wealth prospect regarding to study [mass broad cast media course] in the [Harver University] for &lt;me&gt; to be a professional [News Journalist] ?[Study : Professional Course name(Y.cr),Enter : School name(M.sh),Profession as : Professional category(.pf),Expect wealth luck : (W@wh+x),My adaptability : (S=x)]{A}&lt;S=/M.sh/Y/W@wh+&gt;100.
        /// </summary>
        public static string School005 {
            get {
                return ResourceManager.GetString("School005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will the studying [Journalism] at [North West University] assist &lt;me&gt; to develop future wealth and career as a remarkably professional [Journalist] in &lt;my&gt; life ?[Study : Course name(Y.cr),Enter : School name(M.sh),Profession as : Profession category(O@fh+.pf),Wealth Prospect : (W&amp;wx),Career Future : (Ofx)]{A}&lt;Sn/M.sh/Y/W&amp;w/O@fh+&gt;100.
        /// </summary>
        public static string School006 {
            get {
                return ResourceManager.GetString("School006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can &lt;I&gt; achieve entreprenuriship goal to set up a [software engr. company] by studying [Computer Science] in [Standford University] ?[Establish : Business Category(O@h+.et),Study : Course name(Y.cr),Enter : School name(M.sh),My adaptability : (S=x)]{A}&lt;S=/M.sh/Y/O@h+.et&gt;100.
        /// </summary>
        public static string School007 {
            get {
                return ResourceManager.GetString("School007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will &lt;my&gt; wealth earning competence be enhanced to study [MBA course] in addition to my major [Civil Eng. course] in the future ?[Study optional : Optional course name(Y.cr),Study Major : Major course name(M.cr),Wealth Earning Competence : (W@hw+x),My adaptability : (S=x)]{A}&lt;S=/M/Y/W@hw+&gt;100.
        /// </summary>
        public static string School008 {
            get {
                return ResourceManager.GetString("School008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will the [Harvard univerrsity] bring me a good prospect to be a [politician] for &lt;me&gt; to study [Political Science] there ?[Enter : School name(Y.sh),Profession as : Career goal description(O@fh+.pf),Study : Academic Course name(M.cr),My adaptability : (S=x)]{A}&lt;S=/M/Y/O@fh+&gt;100.
        /// </summary>
        public static string School009 {
            get {
                return ResourceManager.GetString("School009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will it be joyful and fluently for &lt;me&gt; to study at that [Austrilia Sydney University] to complete earning my [master degree in Civil Engineering Science] for next coming [2 years] ?[Study School : School name(Y.sh),Earning Degree in : To earn Learning Drgree(P+),Predict Studying Duration : Select Duration(Tr),joyful and fluently : (S@x)]{OD}&lt;S=n/Ye/P@+&gt;48.0.
        /// </summary>
        public static string School010 {
            get {
                return ResourceManager.GetString("School010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string School011 {
            get {
                return ResourceManager.GetString("School011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string School012 {
            get {
                return ResourceManager.GetString("School012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string School013 {
            get {
                return ResourceManager.GetString("School013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School Application.
        /// </summary>
        public static string School020 {
            get {
                return ResourceManager.GetString("School020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With &lt;my&gt; [school academic score grade]... Can &lt;I&gt; enter [Computer Science bachelor program] at [Harver University] in this coming [summer] ?[ : School / Examination core,Study : Choose academic course(M.cr),Enter : To enter the school&apos;s name(Y.sh),Expecting season/semester/month(T),Entry Admission : (P@x.dc)]{ORm}&lt;S/M.cr/Y/P@.dc&gt;100.
        /// </summary>
        public static string School100 {
            get {
                return ResourceManager.GetString("School100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will the [Architecture department M.S. program] in [Rice University] accept &lt;my&gt; entry application to study in coming next [spring] ?[Study : Apply to study Dept. name(M.cr),Enter : School name(Y.sh), : Coming semester season/month(T),Entry Admission : (P@x.dc)]{ORm}&lt;S/M.cr/Y/P@.dc&gt;100.
        /// </summary>
        public static string School101 {
            get {
                return ResourceManager.GetString("School101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With my [Architecture Dept.] course score records... Will the [Civil Eng. Dept] grand me entry admission to study in next coming [semester] ?[ : Leaving Dept name,Switch to : Switch to Dept. name(Y.sh), : Expecting semester/month(T),Entry Admission : (P@x.dc)]{ORm}&lt;S/Y/P@.dc&gt;100.
        /// </summary>
        public static string School102 {
            get {
                return ResourceManager.GetString("School102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With &lt;my&gt; [Mathematics Dept.] course records at [Denver university]... Can &lt;I&gt; get entry admission to [Computer Science Dept.] at [Harvard university] in coming [summer] ?[ : Leaving Dept. name(.cr), : Leaving school name(.sh),Switch to study : Switch to Dept. name(M.cr),Switch To enter : Switch To school name(Y.sh), : Expecting semester/month(T),Entry Admission : (P@x.dc)]{ORm}&lt;S/M.cr/Y/P@.dc&gt;100.
        /// </summary>
        public static string School103 {
            get {
                return ResourceManager.GetString("School103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Several months passing... &lt;I&gt; sent application to [Australia Sydney university] for admission to study in [Civil Eng.] ... Can &lt;I&gt; get admission... When ?[Enter : School name(Y.sh),Study : Department name(M.cr), : Expecting semester/month(T),Entry Admission : (P@x)]{ORm}&lt;S/M/Y/P@&gt;100.
        /// </summary>
        public static string School104 {
            get {
                return ResourceManager.GetString("School104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With &lt;my&gt; [last year coures scores]... Will &lt;I&gt; be grant for [teaching assistant fellowship] by [Civil Eng. dept.] from [Harvard university] in next coming [year] ?[ : Academic score category,Award : Scholarship category(W@w),Study in : Study department name(Y.cr),Study in : School name(M.sh), : Expecting semester(T)]{ORm}&lt;S/M.sh/Y/W@w&gt;100.
        /// </summary>
        public static string School105 {
            get {
                return ResourceManager.GetString("School105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are several competitive applicants for [research fellowship] in our [Electrnoic Engineering] Deptment... Will &lt;I&gt; be grant it in next coming [summer semester] ?[Apply : Scholarship category(W@w),Study in : Department name(Y.cr), : Expecting semester/month(T)]{ORm}&lt;S/Y/W@w&gt;100.
        /// </summary>
        public static string School106 {
            get {
                return ResourceManager.GetString("School106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can &lt;I&gt; pass the entry examination to get the admission from [Civil Eng. master program] at [Taiwan university] in [this summer semester] ?[Study : Degree Name,Enter : School name(Y.sh), : Expecting semester/month(T),Entry Admission : (P@x.dc)]{ORm}&lt;S/Y/P@.dc&gt;100.
        /// </summary>
        public static string School107 {
            get {
                return ResourceManager.GetString("School107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string School108 {
            get {
                return ResourceManager.GetString("School108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course/Teacher.
        /// </summary>
        public static string School120 {
            get {
                return ResourceManager.GetString("School120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can &lt;I&gt; get the [compulsary Eng. Mathematics] course an above [C pass] score grade from professor [Mr. X] in [this school term] ?[Study : Course Name(.cr),Expecting course grade : Expecting grade(P@+.cg),Professor : Professor Mr. X name(Yn), : Specify school term(T)]{OD}&lt;S/Yn/P@+.cg&gt;100.
        /// </summary>
        public static string School200 {
            get {
                return ResourceManager.GetString("School200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should &lt;I&gt; take this [Advanced Compiler] optional course... Can &lt;I&gt; learn it good enough to get an above [B good grade] from Professor [Mr.X] in [this school term] ?[ : Course name(.cr),Professor : Professor Mr.X name(Yn),Expecting grade : Expecting course grade/score(P@+.cg), : Specify school term(T)]{OD}&lt;S/Yn/P@+.cg&gt;100.
        /// </summary>
        public static string School201 {
            get {
                return ResourceManager.GetString("School201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Professor [Mr. X] the right teacher for (me) to achieve my career goal as a professional [licenced dentist] by studying (his) teaching [Anatomy] course ?[Professor : Professor Mr.X name(Yn),Profession : Professional name(O@+), : Course name(.cr)]{OD}&lt;S/Yn/O@+&gt;100.
        /// </summary>
        public static string School202 {
            get {
                return ResourceManager.GetString("School202", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string School203 {
            get {
                return ResourceManager.GetString("School203", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string School204 {
            get {
                return ResourceManager.GetString("School204", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string School205 {
            get {
                return ResourceManager.GetString("School205", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string School206 {
            get {
                return ResourceManager.GetString("School206", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string School207 {
            get {
                return ResourceManager.GetString("School207", resourceCulture);
            }
        }
    }
}
