//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EditDivineEq.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SubjectText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SubjectText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EditDivineEq.Resources.SubjectText", typeof(SubjectText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13. Business Management.
        /// </summary>
        public static string Business0 {
            get {
                return ResourceManager.GetString("Business0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13.1 Running Diagnosis.
        /// </summary>
        public static string Business1 {
            get {
                return ResourceManager.GetString("Business1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Business10 {
            get {
                return ResourceManager.GetString("Business10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13.2 Product / Goods.
        /// </summary>
        public static string Business2 {
            get {
                return ResourceManager.GetString("Business2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13.3 Advertisement.
        /// </summary>
        public static string Business3 {
            get {
                return ResourceManager.GetString("Business3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13.4 Location.
        /// </summary>
        public static string Business4 {
            get {
                return ResourceManager.GetString("Business4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13.5 Employee.
        /// </summary>
        public static string Business5 {
            get {
                return ResourceManager.GetString("Business5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13.6 Customer.
        /// </summary>
        public static string Business6 {
            get {
                return ResourceManager.GetString("Business6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13.7 Price.
        /// </summary>
        public static string Business7 {
            get {
                return ResourceManager.GetString("Business7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13.8 Sale.
        /// </summary>
        public static string Business8 {
            get {
                return ResourceManager.GetString("Business8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13.9 Profit.
        /// </summary>
        public static string Business9 {
            get {
                return ResourceManager.GetString("Business9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Divine Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14. Entreprenurship.
        /// </summary>
        public static string Entreprenur0 {
            get {
                return ResourceManager.GetString("Entreprenur0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14.1 Investment.
        /// </summary>
        public static string Entreprenur1 {
            get {
                return ResourceManager.GetString("Entreprenur1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14.2 Join Venture.
        /// </summary>
        public static string Entreprenur2 {
            get {
                return ResourceManager.GetString("Entreprenur2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14.3 New Innovation.
        /// </summary>
        public static string Entreprenur3 {
            get {
                return ResourceManager.GetString("Entreprenur3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14.4 Real Estate Layout.
        /// </summary>
        public static string Entreprenur4 {
            get {
                return ResourceManager.GetString("Entreprenur4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Entreprenur5 {
            get {
                return ResourceManager.GetString("Entreprenur5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9. After Marry / Family.
        /// </summary>
        public static string Family0 {
            get {
                return ResourceManager.GetString("Family0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.1 To Have a Baby.
        /// </summary>
        public static string Family1 {
            get {
                return ResourceManager.GetString("Family1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.2 How Love Goes !?.
        /// </summary>
        public static string Family2 {
            get {
                return ResourceManager.GetString("Family2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.3 Divorce.
        /// </summary>
        public static string Family3 {
            get {
                return ResourceManager.GetString("Family3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Family4 {
            get {
                return ResourceManager.GetString("Family4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5. Feng Shui.
        /// </summary>
        public static string FengShui0 {
            get {
                return ResourceManager.GetString("FengShui0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.1 Feng Shui Diagose / Layout.
        /// </summary>
        public static string FengShui1 {
            get {
                return ResourceManager.GetString("FengShui1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FengShui2 {
            get {
                return ResourceManager.GetString("FengShui2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FengShui3 {
            get {
                return ResourceManager.GetString("FengShui3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Auspicious / Ominous.
        /// </summary>
        public static string Good0 {
            get {
                return ResourceManager.GetString("Good0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.1 Auspicious / Ominous State !?.
        /// </summary>
        public static string Good1 {
            get {
                return ResourceManager.GetString("Good1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.2 Ascertain Auspicious / Ominous !?.
        /// </summary>
        public static string Good2 {
            get {
                return ResourceManager.GetString("Good2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.3 Perceive Sick / Life State !?.
        /// </summary>
        public static string Good3 {
            get {
                return ResourceManager.GetString("Good3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Good4 {
            get {
                return ResourceManager.GetString("Good4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10. Health / Medical Care.
        /// </summary>
        public static string Health0 {
            get {
                return ResourceManager.GetString("Health0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.1 Health Diagnosis.
        /// </summary>
        public static string Health1 {
            get {
                return ResourceManager.GetString("Health1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.2 Sick Diagnosis.
        /// </summary>
        public static string Health2 {
            get {
                return ResourceManager.GetString("Health2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.3 Doctor Diagnosis.
        /// </summary>
        public static string Health3 {
            get {
                return ResourceManager.GetString("Health3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.4 Medicine Verfication.
        /// </summary>
        public static string Health4 {
            get {
                return ResourceManager.GetString("Health4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.5 Sugery Diagnosis.
        /// </summary>
        public static string Health5 {
            get {
                return ResourceManager.GetString("Health5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Health6 {
            get {
                return ResourceManager.GetString("Health6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11. House / Real Estate.
        /// </summary>
        public static string House0 {
            get {
                return ResourceManager.GetString("House0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11.1 Health / Wealth Diagnosis.
        /// </summary>
        public static string House1 {
            get {
                return ResourceManager.GetString("House1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11.2 To Buy.
        /// </summary>
        public static string House2 {
            get {
                return ResourceManager.GetString("House2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11.3 To Sell.
        /// </summary>
        public static string House3 {
            get {
                return ResourceManager.GetString("House3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11.4 To Rent.
        /// </summary>
        public static string House4 {
            get {
                return ResourceManager.GetString("House4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11.5 To Lease.
        /// </summary>
        public static string House5 {
            get {
                return ResourceManager.GetString("House5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string House6 {
            get {
                return ResourceManager.GetString("House6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6. Career / Job.
        /// </summary>
        public static string Job0 {
            get {
                return ResourceManager.GetString("Job0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.1 Job Hunting.
        /// </summary>
        public static string Job1 {
            get {
                return ResourceManager.GetString("Job1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.2 Lisence Examination.
        /// </summary>
        public static string Job2 {
            get {
                return ResourceManager.GetString("Job2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.3 Job Diagnosis.
        /// </summary>
        public static string Job3 {
            get {
                return ResourceManager.GetString("Job3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.4 Job Comparsion.
        /// </summary>
        public static string Job4 {
            get {
                return ResourceManager.GetString("Job4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.5 Quantity of Salary / Bonus.
        /// </summary>
        public static string Job5 {
            get {
                return ResourceManager.GetString("Job5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.6 Career Orientation.
        /// </summary>
        public static string Job6 {
            get {
                return ResourceManager.GetString("Job6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.7 Job Security.
        /// </summary>
        public static string Job7 {
            get {
                return ResourceManager.GetString("Job7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.8 Security of Working Origanization.
        /// </summary>
        public static string Job8 {
            get {
                return ResourceManager.GetString("Job8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Job9 {
            get {
                return ResourceManager.GetString("Job9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12. Law Suit / Conflict.
        /// </summary>
        public static string Law0 {
            get {
                return ResourceManager.GetString("Law0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12.1 Negotiation / Conflict.
        /// </summary>
        public static string Law1 {
            get {
                return ResourceManager.GetString("Law1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12.2 Suit Someone.
        /// </summary>
        public static string Law2 {
            get {
                return ResourceManager.GetString("Law2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12.3 Suited By Someone.
        /// </summary>
        public static string Law3 {
            get {
                return ResourceManager.GetString("Law3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12.4 Suiting Result.
        /// </summary>
        public static string Law4 {
            get {
                return ResourceManager.GetString("Law4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Law5 {
            get {
                return ResourceManager.GetString("Law5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8. About To Marry.
        /// </summary>
        public static string Marry0 {
            get {
                return ResourceManager.GetString("Marry0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.1 How Love Goes.
        /// </summary>
        public static string Marry1 {
            get {
                return ResourceManager.GetString("Marry1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.2 Marry Diagnosis.
        /// </summary>
        public static string Marry2 {
            get {
                return ResourceManager.GetString("Marry2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.3 To Marry.
        /// </summary>
        public static string Marry3 {
            get {
                return ResourceManager.GetString("Marry3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Marry4 {
            get {
                return ResourceManager.GetString("Marry4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7. About Romance.
        /// </summary>
        public static string Romance0 {
            get {
                return ResourceManager.GetString("Romance0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7.1 To Date Someone.
        /// </summary>
        public static string Romance1 {
            get {
                return ResourceManager.GetString("Romance1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7.2 How Romance/Love Goes.
        /// </summary>
        public static string Romance2 {
            get {
                return ResourceManager.GetString("Romance2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7.3 Prospect of Marriage.
        /// </summary>
        public static string Romance3 {
            get {
                return ResourceManager.GetString("Romance3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Romance4 {
            get {
                return ResourceManager.GetString("Romance4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. School / Study.
        /// </summary>
        public static string School0 {
            get {
                return ResourceManager.GetString("School0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.1 Predict Prospect(Income/Career).
        /// </summary>
        public static string School1 {
            get {
                return ResourceManager.GetString("School1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.2 Admmision / Scholarship.
        /// </summary>
        public static string School2 {
            get {
                return ResourceManager.GetString("School2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.3 Course Score / Teacher Selection.
        /// </summary>
        public static string School3 {
            get {
                return ResourceManager.GetString("School3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string School4 {
            get {
                return ResourceManager.GetString("School4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SubCategory {
            get {
                return ResourceManager.GetString("SubCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SubStatement {
            get {
                return ResourceManager.GetString("SubStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Trip / Travel.
        /// </summary>
        public static string Trip0 {
            get {
                return ResourceManager.GetString("Trip0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.1 Travel / Tour Trip.
        /// </summary>
        public static string Trip1 {
            get {
                return ResourceManager.GetString("Trip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Trip2 {
            get {
                return ResourceManager.GetString("Trip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4. Wealth / Assets.
        /// </summary>
        public static string Wealth0 {
            get {
                return ResourceManager.GetString("Wealth0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.1 Wealth Luck Diagnosis.
        /// </summary>
        public static string Wealth1 {
            get {
                return ResourceManager.GetString("Wealth1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Wealth2 {
            get {
                return ResourceManager.GetString("Wealth2", resourceCulture);
            }
        }
    }
}
