//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EditDivineEq.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TripText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TripText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EditDivineEq.Resources.TripText", typeof(TripText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How this tour trip around [New York city] will be for &lt;me&gt; in [next coming 2 weeks] ?[Tour around : Destination name(Ya),Predict Duration : Select Duration(Tr),My safety : (Sn@x)]{A}&lt;S@/Ya&gt;32.0.
        /// </summary>
        public static string Trip000 {
            get {
                return ResourceManager.GetString("Trip000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will this trip to visit &lt;my&gt; [brother] [ Mr.X] at [Denver] be happy for &lt;me&gt; in [this coming summer] ?[ : Relative or Firend, : Friend&apos;s / Brother&apos;s name(Yn),Predict Duration : Select Duration(Tr),My happiness : (S@x)]{F}&lt;Sn@/Yn&gt;32.0.
        /// </summary>
        public static string Trip001 {
            get {
                return ResourceManager.GetString("Trip001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will this [Diamond Princess cruise line] touring [around Aegen sea] be safe and happy for &lt;me&gt; within coming [July09 to July20] ?[Boarding on : Transportation/Cruise line name(M.tp),Around : Touring area/router name(Ya),Predict Duration : Select Duration(Tr),My safety : (S@x)]{A}&lt;Sn@/M.tp/Ya&gt;32.0.
        /// </summary>
        public static string Trip002 {
            get {
                return ResourceManager.GetString("Trip002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will this [China Air Flight-038] fly &lt;me&gt; safe from [Taipei] to [Los Angle] in [Jul07 to Jul08] ?[Boarding on : Air plane name &amp; Flight No(M.tp),From City : From city name(Ja),To City : To city name(Ya), : Date of flight(t),My safety : (S@x)]{A}&lt;Sn@/M.tp/Ya/Ja&gt;32.0.
        /// </summary>
        public static string Trip003 {
            get {
                return ResourceManager.GetString("Trip003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will it be safe for &lt;me&gt; to drive [Ford Taurus2020] from [Los Angle] to [Denver] along [I-25 Free High Way] in coming [Aug09 to Aug11 2 days] ?[Drive : Vehicle description(P&amp;.tp),From location : From location(Ja),: To Location : To location(Ya),Along : Along which way(M.ph),Predict Duration : Select Duration(Tr),My safety : (S@x)]{A}&lt;Sn@/M.ph/Ya/P&amp;/Ja&gt;32.0.
        /// </summary>
        public static string Trip004 {
            get {
                return ResourceManager.GetString("Trip004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;I&gt; decide to [walk to the Valley buttom] in [Great Canyon park] to have a sightseeing... How it will be ?[Activity : Discribe activity(Xm), Tour around : Location or Area(Ya),My safety : (S@x)]{A}&lt;Sn@/Ya/Xm&gt;32.0.
        /// </summary>
        public static string Trip005 {
            get {
                return ResourceManager.GetString("Trip005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How &lt;my&gt; money wealth luck will be for &lt;me&gt; to [play pork] in this [Larzarus Casino] in [coming next Friday afternoon] ?{Gamble : Discribe gamble name(Mm),Casino at : Casino name(Ya),Duration : Verify date timing(T),Wealth Luck : (W@wx)]{O}&lt;Sn/Mm/Ya/W@w&gt;32.0.
        /// </summary>
        public static string Trip006 {
            get {
                return ResourceManager.GetString("Trip006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will there be any surprising romantic single [girl] mate &lt;I&gt; can meet by joining this [Lion Travel Agent] toruing group to [Tokoy] in coming [1 week] ?[ : Select girl or boy(n!),Travel with : Travel agent name(Y.et),Touring around : Touring Area(a),Predict Duration : Select Duration(Tr),Wife : (W@!x.sm)]{O}&lt;Sn/Y.et/W@!&gt;32.0.
        /// </summary>
        public static string Trip007 {
            get {
                return ResourceManager.GetString("Trip007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With the [Heart Pacemaker] in my body and [70] years old age, Can &lt;I&gt; safely sustaint a long flight on [China Air Flight-038] from [Taipei] to [Los Angle] in coming [May 20] ?[Auxiliary : Name(.sg), Age : ;Boarding on : Air plane name &amp; Flight No(M.tp),From City : From city name(Ja),To City : To city name(Ya), : Date of flight(t),My Life Safety : (S@x)]{A}&lt;Sn@/M.tp/Ya/Ja&gt;32.0.
        /// </summary>
        public static string Trip008 {
            get {
                return ResourceManager.GetString("Trip008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With the [High Blood Pressure] in my body and [70] years old age, Can &lt;I&gt; safely sustaint a long flight on [China Air Flight-038] from [Taipei] to [Los Angle] in coming [May 20] ?[Sickness : Name(.sg), Age : ;Boarding on : Air plane name &amp; Flight No(M.tp),From City : From city name(Ja),To City : To city name(Ya), : Date of flight(t),My Life Safety : (S@x)]{A}&lt;Sn@/M.tp/Ya/Ja&gt;32.0.
        /// </summary>
        public static string Trip009 {
            get {
                return ResourceManager.GetString("Trip009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Trip010 {
            get {
                return ResourceManager.GetString("Trip010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Trip011 {
            get {
                return ResourceManager.GetString("Trip011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Trip013 {
            get {
                return ResourceManager.GetString("Trip013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Trip014 {
            get {
                return ResourceManager.GetString("Trip014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Trip015 {
            get {
                return ResourceManager.GetString("Trip015", resourceCulture);
            }
        }
    }
}
