//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EditDivineEq.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WealthText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WealthText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EditDivineEq.Resources.WealthText", typeof(WealthText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How is &lt;my&gt; money wealth luck regarding my [Working Bonus] in coming [ 1year]... ?[Wealth Sources : Select your wealth source|EqWealth7(W@w),Predict Duration : Specify the coming days/months(Tr)]{OR?}&lt;Sn/Y/W@w&gt;40.0.
        /// </summary>
        public static string Wealth000 {
            get {
                return ResourceManager.GetString("Wealth000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If &lt;my&gt; [Big Fun Sea Food restaurant] carries this [Honey bread] item/product to sell... I estimate [30.50]% net profit earning with resect to it&apos;s cost, How is the wealth luck for profit in coming [4 month]... ?[ : Business discription / name(S.et),Sell Item : Input the name of product(YC&amp;.go),Net Profit Earning % : Input Expecting Net Profit Earning %(W@wp?),Predict Duration : Specify The Selling duration(Tr)]{AD}&lt;Sn/YC&amp;/W@wp?&gt;80.0.
        /// </summary>
        public static string Wealth001 {
            get {
                return ResourceManager.GetString("Wealth001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is there money wealth luck for &lt;me&gt; to earn [The California Lottery] to buy it&apos;s ticket at [DaWha selling lottery ticket booth] in Next Draw date [FRI/JUN 4, 2021] ?[Lottery Wealth : Lottery Name(W@w),Buy Lottery at : Selling ticket location(Ya.se),On Draw Date : Draw date(t)]{O}&lt;Sn/Ya/W@w&gt;40.0.
        /// </summary>
        public static string Wealth002 {
            get {
                return ResourceManager.GetString("Wealth002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As compare to &lt;my&gt; last [2 yearly] average net earning $[600000.0] quantity for &lt;my&gt; [Lisa Beauty hair style Salon]... How is the quantity of money wealth &lt;I&gt; can earn in next coming [1 year] ?[ : Past Numbering months/years,Mony Earning Quantity : Accurate Quantity of money(W@q$?),Running : Description of business/name(Ye.et),Predict Duration : The coming Yaer/Month(Tr)]{OD}&lt;Sn/Ye.et/W@q?&gt;80.0.
        /// </summary>
        public static string Wealth003 {
            get {
                return ResourceManager.GetString("Wealth003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;I&gt; estimate net earning $[40000.0] quantity to carry [these woman skirts] item at [Arcadia retail store], How much the net earning can earn before tax from these items in next coming [summer 3 months] ?[Money Earning Quantity : Earning quantity of best knowledge(W@q#?),Selling : Product item name(YC&amp;.go),Store at : Store Location(Ya.se),Predict Duration : Duration of sale(Tr)]{OD}&lt;Sn/Ya/C&amp;/W@q?&gt;80.0.
        /// </summary>
        public static string Wealth004 {
            get {
                return ResourceManager.GetString("Wealth004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will the [Harvard University] grand &lt;my&gt; application of [scholarship to do research] in coming [1 year] ?[Study/Work at : Name of the school or origanoization(Y.sh),Wealth/Scholarship : Discription of Scholarship(Ww@),Specify the Calendar Year(t)]{OR}&lt;Sn/Y.sh/Ww@&gt;40.0.
        /// </summary>
        public static string Wealth005 {
            get {
                return ResourceManager.GetString("Wealth005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will [Mr.] [Xname] return the $[50000.0] money that &lt;I&gt; lend to (him) in coming [3 month] ?[ : Select Miss / Mrs. or Mr. for named X person(yn!),Debtor : Debtor name(Yn!),Return wealth quantity : Debt of money quantity(W@wq+),Predicting Duration : Specify the coming days/months(Tr)]{OR}&lt;Sn/Yn!/W@wq+&gt;64.0.
        /// </summary>
        public static string Wealth006 {
            get {
                return ResourceManager.GetString("Wealth006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can &lt;I&gt; get the total quantity of $[600000.0] money loan from the [Wells Fargo bank branch at Arcadia] in next coming [2 months] ?[Wealth/Loan Quantity : Loan Quantity of Money(W@wq$+?),Loan from : Name of the Loan Orgnization(Y.et),Predict Duration : Specify the coming days/months(Tr)]{OR}&lt;Sn/Y/W@wq+?&gt;60.0.
        /// </summary>
        public static string Wealth007 {
            get {
                return ResourceManager.GetString("Wealth007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As compare to last [2] years of [26.5]% annualy average revenue... How many % of the return of revenue will be from &lt;my&gt; holding capital $[880000.0] quantity investing in [Alga Construction Company] in Coming at the end of [1] year ?[ : Input Past number of years(t), : Last 2 years % Return of revenue(wp$), : Quantity of Investing Capital(wq$),Stock Holding : Company/Orgnization name(Ye.et), : Specify this or next year(t),Expect Wealth Return % : (W@p?x)]{OD}&lt;Sn/Ye.et/W@p?&gt;80.0.
        /// </summary>
        public static string Wealth008 {
            get {
                return ResourceManager.GetString("Wealth008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will the price of &lt;my&gt; currently holding [Securities/Stocks of Apple Company] be raised [10]% up above &lt;my&gt; buying price after [6 months] ?[Hold Asset : Discription/Name of securities(Y.sc),Expect Wealth Earning % : Expect % above the buying Price(W@p?),Predict Duration : Specify holding duration(Tr)]{OD}&lt;Sn/Y.sc/W@p?&gt;80.0.
        /// </summary>
        public static string Wealth009 {
            get {
                return ResourceManager.GetString("Wealth009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;I&gt; plan to buy the [Apple Company&apos;s Securities/Stocks] at it&apos;s current market price....  Will it&apos;s price be raised up by market above [10]% in next coming [6 months] ?[Hold Asset : Discription/Name of securities(Y.sc),Expect Wealth Earning % : Expect % above current market price(W@p?),Predict Duration : Specify holding duratio(Tr)]{OD}&lt;Sn/Y/W@p?&gt;80.0.
        /// </summary>
        public static string Wealth010 {
            get {
                return ResourceManager.GetString("Wealth010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;I&gt; estimate [16]% to [20]% of annually return revenue for &lt;my&gt; share holding $[800000.0] in [Samuel Construction Company]... How many % of the revenue will be in coming in the end year of [2021] ?[ : Least earning %(wp1#), : Highest earning %(wp2#), : Share Holding Quantity(wq$),Hold Asset : Company name(Y.et), : This or next coming year(t),Expect Wealth Earning % : %(W@p?x)]{OD}&lt;Sn/Y/W@p?&gt;80.0.
        /// </summary>
        public static string Wealth011 {
            get {
                return ResourceManager.GetString("Wealth011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How is the future prospect regarding &lt;my&gt; wealth income and [Mental consolation Clinic] business development lucks... If &lt;I&gt; move to [ Taiwan Taipei ] in coming [12] years ?[Business/Career : Business/Career description(O.et),Move To Region : Intend Move in Area/Region(Ya.se),Predict Duration : Specify future duration(Tr),Wealth Luck : (W&amp;x)]{OD}&lt;Sn/Ya/W&amp;+/O@+&gt;80.0 .
        /// </summary>
        public static string Wealth012 {
            get {
                return ResourceManager.GetString("Wealth012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;I&gt; intend to buy [1530 W. Durate Rd. Arcadia CA. 91007 real estate] at it&apos;s current $[680000.0] market appraisal Price... Will it&apos;s price be raised above [10]% by market in the future [2 years] ?[Real Estate at : Property address(Ya.ho.lv), : Current appraisal prise(wq$),Expect Wealth Earning above % : Expect raising up %(W@p?),Predicting Duration : How many year to hold(Tr)]{OD}&lt;Sn/Ya.ho.lv/W@p?&gt;80.0.
        /// </summary>
        public static string Wealth013 {
            get {
                return ResourceManager.GetString("Wealth013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How is the business and wealth earnings futue prosect for &lt;my&gt; [Lisa Beauty Hair style salon] business to move from current [San Franscisco] location to new [Los Angle] location will be in coming [12 years]... ?[Business : describe business and name(Y.et),Current Location Effect : Current Address/City/Country(Ja),Switch To Location Effect : Switch To Address/City/Country(Ka),Predict Duration : Select Duration(Tr),Wealth Prospect : (W&amp;x),Business Prospect : (O@x),Current Region Effect : (Jx),Switch To Region [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Wealth014 {
            get {
                return ResourceManager.GetString("Wealth014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Wealth015 {
            get {
                return ResourceManager.GetString("Wealth015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Wealth016 {
            get {
                return ResourceManager.GetString("Wealth016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?): unknown, (O): Obtain_Lose, (w): wealth Select your wealth source|EqWealth7(W@w;  Select (|) Options.
        /// </summary>
        public static string Wealth017 {
            get {
                return ResourceManager.GetString("Wealth017", resourceCulture);
            }
        }
    }
}
